import { MEDICAL_ILLUSTRATIONS } from '@/constants/medical-illustrations';

export const HOSPITALS_DATA = [
  {
    name: "Hitas Super Speciality Hospital",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop",
    location: "Banjara Hills, Hyderabad",
    distance: "< 2.5 km",
    fee: "₹1500 onwards",
    nextAvailable: "Today, 02:00 PM",
    rating: "4.6",
    speciality: "Multi Speciality Hospital",
    departments: "Cardiology • Neurology • +12 more",
  },
  {
    name: "Fortis Healthcare",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop",
    logo: "https://download.logo.wine/logo/Fortis_Healthcare/Fortis_Healthcare-Logo.wine.png",
    location: "Cunningham Road",
    distance: "4.1 km away",
    fee: "₹800 onwards",
    nextAvailable: "Today, 02:00 PM",
    rating: "4.6",
    speciality: "World class healthcare delivery system.",
    departments: "Cardiology • Neurology • +12 more",
  },
  {
    name: "Apollo Hospitals",
    image: "https://images.unsplash.com/photo-1538108149393-cebb47cdf14d?q=80&w=2069&auto=format&fit=crop",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Apollo_Hospitals_Logo.svg/1200px-Apollo_Hospitals_Logo.svg.png",
    location: "Jubilee Hills",
    distance: "3.2 km away",
    fee: "₹1200 onwards",
    nextAvailable: "Today, 04:30 PM",
    rating: "4.8",
    speciality: "Advanced Care & Surgery",
    departments: "Oncology • Orthopedics • +15 more",
  },
  {
    name: "Manipal Hospitals",
    image: "https://images.unsplash.com/photo-1587351021355-a479a299d2f9?q=80&w=2072&auto=format&fit=crop",
    logo: "https://companieslogo.com/img/orig/MANIPAL.NS-e4d3a246.png",
    location: "Old Airport Road",
    distance: "6.5 km away",
    fee: "₹1000 onwards",
    nextAvailable: "Tomorrow, 09:00 AM",
    rating: "4.7",
    speciality: "Comprehensive Medical Care",
    departments: "Pediatrics • Gynecology • +10 more",
  },
  {
    name: "Aster CMI Hospital",
    image: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=2074&auto=format&fit=crop",
    logo: "https://seeklogo.com/images/A/aster-dm-healthcare-logo-5D5BCB5B6D-seeklogo.com.png",
    location: "Hebbal",
    distance: "8.0 km away",
    fee: "₹1100 onwards",
    nextAvailable: "Today, 06:00 PM",
    rating: "4.5",
    speciality: "Quaternary Care Hospital",
    departments: "Gastroenterology • Urology • +8 more",
  },
  {
    name: "Narayana Health",
    image: "https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?q=80&w=2058&auto=format&fit=crop",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Narayana_Health_Logo.svg/1200px-Narayana_Health_Logo.svg.png",
    location: "Bommasandra",
    distance: "12 km away",
    fee: "₹900 onwards",
    nextAvailable: "Today, 01:00 PM",
    rating: "4.4",
    speciality: "Cardiac Sciences & Multispecialty",
    departments: "Cardiac Surgery • Neurology • +14 more",
  },
  {
    name: "Sakra World Hospital",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop",
    location: "Bellandur",
    distance: "5.5 km away",
    fee: "₹1300 onwards",
    nextAvailable: "Tomorrow, 10:30 AM",
    rating: "4.6",
    speciality: "Indo-Japanese Medical Excellence",
    departments: "Orthopedics • Neurosciences • +9 more",
  },
  {
    name: "Sparsh Hospital",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop",
    location: "Yeshwanthpur",
    distance: "9.2 km away",
    fee: "₹850 onwards",
    nextAvailable: "Today, 05:00 PM",
    rating: "4.5",
    speciality: "Advanced Orthopedic Care",
    departments: "Orthopedics • Rheumatology • +6 more",
  },
  {
    name: "Cloudnine Hospital",
    image: "https://images.unsplash.com/photo-1538108149393-cebb47cdf14d?q=80&w=2069&auto=format&fit=crop",
    location: "Jayanagar",
    distance: "2.8 km away",
    fee: "₹1000 onwards",
    nextAvailable: "Today, 03:15 PM",
    rating: "4.8",
    speciality: "Maternity & Childcare",
    departments: "Maternity • Pediatrics • +4 more",
  },
  {
    name: "Motherhood Hospital",
    image: "https://images.unsplash.com/photo-1587351021355-a479a299d2f9?q=80&w=2072&auto=format&fit=crop",
    location: "Indiranagar",
    distance: "3.5 km away",
    fee: "₹950 onwards",
    nextAvailable: "Tomorrow, 11:00 AM",
    rating: "4.7",
    speciality: "Women & Children's Hospital",
    departments: "Gynecology • Neonatology • +5 more",
  },
  {
    name: "AIG Hospitals",
    image: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=2074&auto=format&fit=crop",
    location: "Gachibowli",
    distance: "4.0 km away",
    fee: "₹1400 onwards",
    nextAvailable: "Today, 04:00 PM",
    rating: "4.9",
    speciality: "Asian Institute of Gastroenterology",
    departments: "Gastroenterology • Hepatology • +11 more",
  },
  {
    name: "Care Hospitals",
    image: "https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?q=80&w=2058&auto=format&fit=crop",
    location: "Hi-Tech City",
    distance: "5.1 km away",
    fee: "₹1100 onwards",
    nextAvailable: "Today, 02:30 PM",
    rating: "4.5",
    speciality: "Multispecialty Care",
    departments: "Cardiology • Nephrology • +10 more",
  },
  {
    name: "KIMS Hospitals",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop",
    location: "Secunderabad",
    distance: "7.8 km away",
    fee: "₹1200 onwards",
    nextAvailable: "Tomorrow, 09:30 AM",
    rating: "4.6",
    speciality: "Krishna Institute of Medical Sciences",
    departments: "Neurology • Pulmonology • +12 more",
  },
  {
    name: "Yashoda Hospitals",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop",
    location: "Somajiguda",
    distance: "3.9 km away",
    fee: "₹1300 onwards",
    nextAvailable: "Today, 06:15 PM",
    rating: "4.7",
    speciality: "Advanced Super Specialty Care",
    departments: "Oncology • Cardiology • +14 more",
  },
  {
    name: "Sunshine Hospitals",
    image: "https://images.unsplash.com/photo-1538108149393-cebb47cdf14d?q=80&w=2069&auto=format&fit=crop",
    location: "Paradise Circle",
    distance: "6.2 km away",
    fee: "₹900 onwards",
    nextAvailable: "Today, 01:45 PM",
    rating: "4.5",
    speciality: "Orthopedic & Multispecialty",
    departments: "Orthopedics • Joint Replacement • +8 more",
  },
  {
    name: "Continental Hospitals",
    image: "https://images.unsplash.com/photo-1587351021355-a479a299d2f9?q=80&w=2072&auto=format&fit=crop",
    location: "Financial District",
    distance: "8.5 km away",
    fee: "₹1500 onwards",
    nextAvailable: "Tomorrow, 10:00 AM",
    rating: "4.8",
    speciality: "JCI Accredited Facility",
    departments: "Oncology • Neurosciences • +11 more",
  },
  {
    name: "Medicover Hospitals",
    image: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=2074&auto=format&fit=crop",
    location: "Madhapur",
    distance: "4.7 km away",
    fee: "₹1000 onwards",
    nextAvailable: "Today, 05:30 PM",
    rating: "4.4",
    speciality: "European Standard Healthcare",
    departments: "Internal Medicine • Surgery • +10 more",
  },
  {
    name: "Omni Hospitals",
    image: "https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?q=80&w=2058&auto=format&fit=crop",
    location: "Kothapet",
    distance: "10.2 km away",
    fee: "₹750 onwards",
    nextAvailable: "Today, 12:30 PM",
    rating: "4.3",
    speciality: "Affordable Super Specialty",
    departments: "General Medicine • Orthopedics • +7 more",
  },
  {
    name: "Star Hospitals",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop",
    location: "Banjara Hills",
    distance: "2.1 km away",
    fee: "₹1100 onwards",
    nextAvailable: "Tomorrow, 08:30 AM",
    rating: "4.6",
    speciality: "Pioneers in Cardiac Care",
    departments: "Cardiology • ENT • +9 more",
  },
  {
    name: "Pristyn Care",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop",
    location: "HSR Layout",
    distance: "5.8 km away",
    fee: "₹500 onwards",
    nextAvailable: "Today, 03:00 PM",
    rating: "4.7",
    speciality: "Advanced Surgical Centers",
    departments: "Proctology • Urology • +6 more",
  }
];

export const GYMS_DATA = [
  {
    title: "Cult.fit Center",
    subtitle: "State of the art fitness equipment.",
    image: MEDICAL_ILLUSTRATIONS.fitness,
    logo: "https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_120,q_auto:eco,dpr_2,f_auto,fl_progressive//image/test/brand-logo/vman-and-white-cult-text.png",
    typeTag: "Premium Gym",
    address: "Indiranagar",
    distance: "1.2 km away",
    fee: "₹1500/mo",
    nextAvailable: "Open Now",
    insurance: "N/A",
    trustedCount: "5,000+",
    rating: "4.9",
    reviews: "3.5K",
  },
  {
    title: "Gold's Gym",
    subtitle: "Legacy of strength and fitness.",
    image: MEDICAL_ILLUSTRATIONS.weightLoss,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Gold%27s_Gym_logo.svg/1200px-Gold%27s_Gym_logo.svg.png",
    typeTag: "Fitness Studio",
    address: "Koramangala",
    distance: "3.0 km away",
    fee: "₹2000/mo",
    nextAvailable: "Open 24x7",
    insurance: "N/A",
    trustedCount: "15,000+",
    rating: "4.5",
    reviews: "8.1K",
  },
  {
    title: "Anytime Fitness",
    subtitle: "Your fitness, anytime, anywhere.",
    image: MEDICAL_ILLUSTRATIONS.fitness,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Anytime_Fitness_logo.svg/2560px-Anytime_Fitness_logo.svg.png",
    typeTag: "24/7 Gym",
    address: "HSR Layout",
    distance: "2.4 km away",
    fee: "₹1800/mo",
    nextAvailable: "Open 24x7",
    insurance: "N/A",
    trustedCount: "8,200+",
    rating: "4.7",
    reviews: "2.1K",
  },
  {
    title: "Snap Fitness",
    subtitle: "Fast, convenient and affordable.",
    image: MEDICAL_ILLUSTRATIONS.weightLoss,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Snap_Fitness_Logo.png",
    typeTag: "Fitness Center",
    address: "Whitefield",
    distance: "5.1 km away",
    fee: "₹1200/mo",
    nextAvailable: "Open Now",
    insurance: "N/A",
    trustedCount: "3,400+",
    rating: "4.4",
    reviews: "950",
  },
  {
    title: "F45 Training",
    subtitle: "Team training, life changing.",
    image: MEDICAL_ILLUSTRATIONS.fitness,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/F45_Training_logo.svg/1200px-F45_Training_logo.svg.png",
    typeTag: "HIIT Studio",
    address: "Jubilee Hills",
    distance: "4.5 km away",
    fee: "₹3500/mo",
    nextAvailable: "Closes 9 PM",
    insurance: "N/A",
    trustedCount: "2,000+",
    rating: "4.9",
    reviews: "1.2K",
  }
];

export const REHABS_DATA = [
  {
    title: "Hope Rehab Clinic",
    subtitle: "Expert care for complete recovery.",
    image: MEDICAL_ILLUSTRATIONS.rehab,
    logo: "https://cdn-icons-png.flaticon.com/512/2966/2966327.png",
    typeTag: "Rehabilitation Center",
    address: "HSR Layout",
    distance: "2.5 km away",
    fee: "₹1200 onwards",
    nextAvailable: "Today, 04:00 PM",
    insurance: "10+ Providers",
    trustedCount: "2,500+",
    rating: "4.8",
    reviews: "950",
  },
  {
    title: "Nightingale Care",
    subtitle: "Post-surgery recovery and care.",
    image: MEDICAL_ILLUSTRATIONS.homeCare,
    logo: "https://cdn-icons-png.flaticon.com/512/2966/2966327.png",
    typeTag: "Recovery Center",
    address: "BTM Layout",
    distance: "3.2 km away",
    fee: "₹1500 onwards",
    nextAvailable: "Tomorrow, 10:00 AM",
    insurance: "15+ Providers",
    trustedCount: "4,100+",
    rating: "4.7",
    reviews: "1.1K",
  }
];

export const CLINICS_DATA = [
  {
    title: "Arogyon Family Clinic",
    subtitle: "Doctors, nurses, labs and pharmacy under one roof.",
    image: MEDICAL_ILLUSTRATIONS.clinic,
    logo: "https://cdn-icons-png.flaticon.com/512/2966/2966327.png",
    typeTag: "Primary Care Clinic",
    address: "Indiranagar",
    distance: "1.1 km away",
    fee: "INR 350 onwards",
    nextAvailable: "Today, 05:30 PM",
    insurance: "18+ Providers",
    trustedCount: "6,200+",
    rating: "4.7",
    reviews: "1.1K",
  },
  {
    title: "Arogyon Care at Home",
    subtitle: "Nursing, eldercare and recovery support at home.",
    image: MEDICAL_ILLUSTRATIONS.homeCare,
    logo: "https://cdn-icons-png.flaticon.com/512/2966/2966327.png",
    typeTag: "Home Care Team",
    address: "Whitefield",
    distance: "3.4 km away",
    fee: "INR 900 onwards",
    nextAvailable: "Today, 07:00 PM",
    insurance: "12+ Providers",
    trustedCount: "3,800+",
    rating: "4.8",
    reviews: "860",
  },
  {
    title: "Apollo Clinic",
    subtitle: "Everyday healthcare for everyday people.",
    image: MEDICAL_ILLUSTRATIONS.clinic,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Apollo_Hospitals_Logo.svg/1200px-Apollo_Hospitals_Logo.svg.png",
    typeTag: "Multispecialty Clinic",
    address: "Koramangala",
    distance: "2.1 km away",
    fee: "INR 500 onwards",
    nextAvailable: "Today, 04:15 PM",
    insurance: "20+ Providers",
    trustedCount: "9,000+",
    rating: "4.6",
    reviews: "2.5K",
  }
];
