import { MEDICAL_ILLUSTRATIONS } from '@/constants/medical-illustrations';

export const HOSPITALS_DATA = [
  {
    id: "hosp-1",
    name: "Hitas Super Speciality Hospital",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop",
    location: "Banjara Hills, Hyderabad",
    distance: "< 2.5 km",
    fee: "₹1500 onwards",
    nextAvailable: "24x7",
    rating: "4.6",
    speciality: "Multi Speciality Hospital",
    departments: "Cardiology • Neurology • +12 more",
    category: "Hospitals",
  },
  {
    id: "hosp-2",
    name: "Fortis Healthcare",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop",
    logo: "https://download.logo.wine/logo/Fortis_Healthcare/Fortis_Healthcare-Logo.wine.png",
    location: "Cunningham Road, Bangalore",
    distance: "4.1 km away",
    fee: "₹800 onwards",
    nextAvailable: "8 AM - 10 PM",
    rating: "4.6",
    speciality: "World class healthcare delivery system.",
    departments: "Cardiology • Neurology • +12 more",
    category: "Hospitals",
  },
  {
    id: "hosp-3",
    name: "Lenskart Vision & Eye Health Center",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=2070&auto=format&fit=crop",
    logo: "https://cdn.iconscout.com/icon/free/png-256/free-lenskart-logo-icon-download-in-svg-png-gif-file-formats--brand-social-media-pack-logos-icons-2264878.png",
    location: "Indiranagar, Bangalore",
    distance: "1.8 km away",
    fee: "₹499 onwards",
    nextAvailable: "10 AM - 9 PM",
    rating: "4.9",
    speciality: "Lenskart Eye Care & Vision Center",
    departments: "Vision Test • Retina Check • Computer Glasses",
    category: "Eye Care",
  },
  {
    id: "hosp-4",
    name: "Apollo Hospitals",
    image: "https://images.unsplash.com/photo-1538108149393-cebb47cdf14d?q=80&w=2069&auto=format&fit=crop",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Apollo_Hospitals_Logo.svg/1200px-Apollo_Hospitals_Logo.svg.png",
    location: "Jubilee Hills, Hyderabad",
    distance: "3.2 km away",
    fee: "₹1200 onwards",
    nextAvailable: "9 AM - 9 PM",
    rating: "4.8",
    speciality: "Advanced Care & Surgery",
    departments: "Oncology • Orthopedics • +15 more",
    category: "Hospitals",
  },
  {
    id: "hosp-5",
    name: "Dr. Agarwal's Eye Hospital",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=2070&auto=format&fit=crop",
    location: "Koramangala, Bangalore",
    distance: "2.4 km away",
    fee: "₹700 onwards",
    nextAvailable: "9 AM - 8 PM",
    rating: "4.8",
    speciality: "Super Speciality Eye Care & Lasik",
    departments: "Cataract • Cornea • Retina Surgery",
    category: "Eye Care",
  },
  {
    id: "hosp-6",
    name: "Clove Dental Super Speciality",
    image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=2070&auto=format&fit=crop",
    location: "HSR Layout, Bangalore",
    distance: "2.1 km away",
    fee: "₹500 onwards",
    nextAvailable: "9 AM - 9 PM",
    rating: "4.8",
    speciality: "Advanced Dental Care & Implants",
    departments: "Root Canal • Orthodontics • Teeth Whitening",
    category: "Dental Care",
  },
  {
    id: "hosp-7",
    name: "Manipal Hospitals",
    image: "https://images.unsplash.com/photo-1587351021355-a479a299d2f9?q=80&w=2072&auto=format&fit=crop",
    logo: "https://companieslogo.com/img/orig/MANIPAL.NS-e4d3a246.png",
    location: "Old Airport Road, Bangalore",
    distance: "6.5 km away",
    fee: "₹1000 onwards",
    nextAvailable: "24x7",
    rating: "4.7",
    speciality: "Comprehensive Medical Care",
    departments: "Pediatrics • Gynecology • +10 more",
    category: "Hospitals",
  },
  {
    id: "hosp-8",
    name: "Narayana Nethralaya",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=2070&auto=format&fit=crop",
    location: "Rajajinagar, Bangalore",
    distance: "5.2 km away",
    fee: "₹800 onwards",
    nextAvailable: "8 AM - 7 PM",
    rating: "4.9",
    speciality: "Super Speciality Eye Hospital",
    departments: "Lasik • Glaucoma • Ocular Oncology",
    category: "Eye Care",
  },
  {
    id: "hosp-9",
    name: "Partha Dental & Maxillofacial Center",
    image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=2070&auto=format&fit=crop",
    location: "Banjara Hills, Hyderabad",
    distance: "3.5 km away",
    fee: "₹600 onwards",
    nextAvailable: "10 AM - 8 PM",
    rating: "4.7",
    speciality: "Cosmetic & Implant Dentistry",
    departments: "Smile Design • Dental Implants • Braces",
    category: "Dental Care",
  },
  {
    id: "hosp-10",
    name: "Aster CMI Hospital",
    image: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=2074&auto=format&fit=crop",
    logo: "https://seeklogo.com/images/A/aster-dm-healthcare-logo-5D5BCB5B6D-seeklogo.com.png",
    location: "Hebbal, Bangalore",
    distance: "8.0 km away",
    fee: "₹1100 onwards",
    nextAvailable: "10 AM - 8 PM",
    rating: "4.5",
    speciality: "Quaternary Care Hospital",
    departments: "Gastroenterology • Urology • +8 more",
    category: "Hospitals",
  },
  {
    id: "hosp-11",
    name: "Vasan Eye Care Hospital",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=2070&auto=format&fit=crop",
    location: "Jayanagar, Bangalore",
    distance: "4.0 km away",
    fee: "₹650 onwards",
    nextAvailable: "9 AM - 8 PM",
    rating: "4.6",
    speciality: "Premier Eye Care Network",
    departments: "Cataract • Squint Care • Contact Lens Clinic",
    category: "Eye Care",
  },
  {
    id: "hosp-12",
    name: "Apollo Dental Clinic",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=2070&auto=format&fit=crop",
    location: "Whitefield, Bangalore",
    distance: "4.8 km away",
    fee: "₹750 onwards",
    nextAvailable: "9 AM - 8 PM",
    rating: "4.7",
    speciality: "Multispecialty Dental Care",
    departments: "Laser Dentistry • Pediatric Dental • Aligners",
    category: "Dental Care",
  },
  {
    id: "hosp-13",
    name: "Narayana Health",
    image: "https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?q=80&w=2058&auto=format&fit=crop",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Narayana_Health_Logo.svg/1200px-Narayana_Health_Logo.svg.png",
    location: "Bommasandra, Bangalore",
    distance: "12 km away",
    fee: "₹900 onwards",
    nextAvailable: "24x7",
    rating: "4.4",
    speciality: "Cardiac Sciences & Multispecialty",
    departments: "Cardiac Surgery • Neurology • +14 more",
    category: "Hospitals",
  },
  {
    id: "hosp-14",
    name: "Centre For Sight Eye Institute",
    image: "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?q=80&w=2070&auto=format&fit=crop",
    location: "Gachibowli, Hyderabad",
    distance: "4.2 km away",
    fee: "₹850 onwards",
    nextAvailable: "9 AM - 7 PM",
    rating: "4.8",
    speciality: "Advanced Lasik & Cornea Center",
    departments: "SMILE Lasik • Cornea Transplant • Retina",
    category: "Eye Care",
  },
  {
    id: "hosp-15",
    name: "Sabka Dentist Clinic",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?q=80&w=2070&auto=format&fit=crop",
    location: "Koramangala, Bangalore",
    distance: "3.1 km away",
    fee: "₹450 onwards",
    nextAvailable: "10 AM - 9 PM",
    rating: "4.5",
    speciality: "Affordable Family Dentistry",
    departments: "Scaling • Aligners • Tooth Extraction",
    category: "Dental Care",
  },
  {
    id: "hosp-16",
    name: "Sakra World Hospital",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2073&auto=format&fit=crop",
    location: "Bellandur, Bangalore",
    distance: "5.5 km away",
    fee: "₹1300 onwards",
    nextAvailable: "8 AM - 11 PM",
    rating: "4.6",
    speciality: "Indo-Japanese Medical Excellence",
    departments: "Orthopedics • Neurosciences • +9 more",
    category: "Hospitals",
  },
  {
    id: "hosp-17",
    name: "Sparsh Hospital",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop",
    location: "Yeshwanthpur, Bangalore",
    distance: "9.2 km away",
    fee: "₹850 onwards",
    nextAvailable: "9 AM - 6 PM",
    rating: "4.5",
    speciality: "Advanced Orthopedic Care",
    departments: "Orthopedics • Rheumatology • +6 more",
    category: "Hospitals",
  },
  {
    id: "hosp-18",
    name: "Cloudnine Hospital",
    image: "https://images.unsplash.com/photo-1538108149393-cebb47cdf14d?q=80&w=2069&auto=format&fit=crop",
    location: "Jayanagar, Bangalore",
    distance: "2.8 km away",
    fee: "₹1000 onwards",
    nextAvailable: "24x7",
    rating: "4.8",
    speciality: "Maternity & Childcare",
    departments: "Maternity • Pediatrics • +4 more",
    category: "Hospitals",
  },
  {
    id: "hosp-19",
    name: "AIG Hospitals",
    image: "https://images.unsplash.com/photo-1512678080530-7760d81faba6?q=80&w=2074&auto=format&fit=crop",
    location: "Gachibowli, Hyderabad",
    distance: "4.0 km away",
    fee: "₹1400 onwards",
    nextAvailable: "9 AM - 9 PM",
    rating: "4.9",
    speciality: "Asian Institute of Gastroenterology",
    departments: "Gastroenterology • Hepatology • +11 more",
    category: "Hospitals",
  },
  {
    id: "hosp-20",
    name: "Care Hospitals",
    image: "https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?q=80&w=2058&auto=format&fit=crop",
    location: "Hi-Tech City, Hyderabad",
    distance: "5.1 km away",
    fee: "₹1100 onwards",
    nextAvailable: "24x7",
    rating: "4.5",
    speciality: "Multispecialty Care",
    departments: "Cardiology • Nephrology • +10 more",
    category: "Hospitals",
  }
];

export const GYMS_DATA = [
  {
    title: "Cult.fit Center",
    subtitle: "State of the art fitness equipment.",
    image: MEDICAL_ILLUSTRATIONS.fitness,
    logo: "https://cdn-images.cure.fit/www-curefit-com/image/upload/c_fill,w_120,q_auto:eco,dpr_2,f_auto,fl_progressive//image/test/brand-logo/vman-and-white-cult-text.png",
    typeTag: "Premium Gym",
    address: "Indiranagar",
    distance: "1.2 km away",
    fee: "₹1500/mo",
    nextAvailable: "10 AM - 8 PM",
    insurance: "N/A",
    trustedCount: "5,000+",
    rating: "4.9",
    reviews: "3.5K",
  },
  {
    title: "Gold's Gym",
    subtitle: "Legacy of strength and fitness.",
    image: MEDICAL_ILLUSTRATIONS.weightLoss,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Gold%27s_Gym_logo.svg/1200px-Gold%27s_Gym_logo.svg.png",
    typeTag: "Fitness Studio",
    address: "Koramangala",
    distance: "3.0 km away",
    fee: "₹2000/mo",
    nextAvailable: "24x7",
    insurance: "N/A",
    trustedCount: "15,000+",
    rating: "4.5",
    reviews: "8.1K",
  },
  {
    title: "Anytime Fitness",
    subtitle: "Your fitness, anytime, anywhere.",
    image: MEDICAL_ILLUSTRATIONS.fitness,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Anytime_Fitness_logo.svg/2560px-Anytime_Fitness_logo.svg.png",
    typeTag: "24/7 Gym",
    address: "HSR Layout",
    distance: "2.4 km away",
    fee: "₹1800/mo",
    nextAvailable: "8 AM - 11 PM",
    insurance: "N/A",
    trustedCount: "8,200+",
    rating: "4.7",
    reviews: "2.1K",
  },
  {
    title: "Snap Fitness",
    subtitle: "Fast, convenient and affordable.",
    image: MEDICAL_ILLUSTRATIONS.weightLoss,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Snap_Fitness_Logo.png",
    typeTag: "Fitness Center",
    address: "Whitefield",
    distance: "5.1 km away",
    fee: "₹1200/mo",
    nextAvailable: "9 AM - 6 PM",
    insurance: "N/A",
    trustedCount: "3,400+",
    rating: "4.4",
    reviews: "950",
  },
  {
    title: "F45 Training",
    subtitle: "Team training, life changing.",
    image: MEDICAL_ILLUSTRATIONS.fitness,
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/F45_Training_logo.svg/1200px-F45_Training_logo.svg.png",
    typeTag: "HIIT Studio",
    address: "Jubilee Hills",
    distance: "4.5 km away",
    fee: "₹3500/mo",
    nextAvailable: "24x7",
    insurance: "N/A",
    trustedCount: "2,000+",
    rating: "4.9",
    reviews: "1.2K",
  }
];

export const CLINICS_DATA = [
  {
    title: "Arogyon Family Clinic",
    subtitle: "Doctors, nurses, labs and pharmacy under one roof.",
    image: MEDICAL_ILLUSTRATIONS.clinic,
    logo: "https://cdn-icons-png.flaticon.com/512/2966/2966327.png",
    typeTag: "Primary Care Clinic",
    address: "Indiranagar",
    distance: "1.1 km away",
    fee: "INR 350 onwards",
    nextAvailable: "24x7",
    insurance: "18+ Providers",
    trustedCount: "6,200+",
    rating: "4.7",
    reviews: "1.1K",
  },
  {
    title: "Arogyon Care at Home",
    subtitle: "Nursing, eldercare and recovery support at home.",
    image: MEDICAL_ILLUSTRATIONS.homeCare,
    logo: "https://cdn-icons-png.flaticon.com/512/2966/2966327.png",
    typeTag: "Home Care Team",
    address: "Whitefield",
    distance: "3.4 km away",
    fee: "INR 900 onwards",
    nextAvailable: "10 AM - 8 PM",
    insurance: "12+ Providers",
    trustedCount: "3,800+",
    rating: "4.8",
    reviews: "860",
  },
  {
    title: "Apollo Clinic",
    subtitle: "Everyday healthcare for everyday people.",
    image: MEDICAL_ILLUSTRATIONS.clinic,
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Apollo_Hospitals_Logo.svg/1200px-Apollo_Hospitals_Logo.svg.png",
    typeTag: "Multispecialty Clinic",
    address: "Koramangala",
    distance: "2.1 km away",
    fee: "INR 500 onwards",
    nextAvailable: "24x7",
    insurance: "20+ Providers",
    trustedCount: "9,000+",
    rating: "4.6",
    reviews: "2.5K",
  }
];
