import { MEDICAL_ILLUSTRATIONS } from '@/constants/medical-illustrations';

export const HEALTH_SYSTEMS = [
  { id: 'clinical', name: 'Clinical', icon: 'stethoscope', color: '#00cec9', gradient: ['#00cec9', '#0878d9'] },
  { id: 'ayurveda', name: 'Ayurveda', icon: 'leaf', color: '#ffb142', gradient: ['#ffb142', '#cc8e35'] },
  { id: 'homeopathy', name: 'Homeopathy', icon: 'droplets', color: '#6c5ce7', gradient: ['#6c5ce7', '#a29bfe'] },
  { id: 'diagnostic', name: 'Diagnostic', icon: 'microscope', color: '#ff7675', gradient: ['#ff7675', '#d63031'] },
];

export const SERVICE_CATEGORIES = [
  { id: 'clinical', name: 'Clinical Hub', icon: 'Stethoscope', image: MEDICAL_ILLUSTRATIONS.clinical },
  { id: 'gastro', name: 'Gastroenterology', icon: 'Activity', image: MEDICAL_ILLUSTRATIONS.gastro },
  { id: 'pulmo', name: 'Pulmonology', icon: 'Activity', image: MEDICAL_ILLUSTRATIONS.pulmonology },
  { id: 'cardio', name: 'Cardiology', icon: 'Heart', image: MEDICAL_ILLUSTRATIONS.cardiology },
  { id: 'gynecology', name: 'Gynecology', icon: 'Activity', image: MEDICAL_ILLUSTRATIONS.gynecology },
  { id: 'orthopedics', name: 'Orthopedics', icon: 'Activity', image: MEDICAL_ILLUSTRATIONS.orthopedics },
  { id: 'physio', name: 'Physiotherapy', icon: 'Activity', image: MEDICAL_ILLUSTRATIONS.physiotherapy },
  { id: 'homeopathy', name: 'Homeopathy', icon: 'Droplets', image: MEDICAL_ILLUSTRATIONS.homeopathy },
  { id: 'diagnostics', name: 'Diagnostics', icon: 'Microscope', image: MEDICAL_ILLUSTRATIONS.diagnostics },
  { id: 'insurance', name: 'Insurance', icon: 'ShieldCheck', image: MEDICAL_ILLUSTRATIONS.insurance },
  { id: 'home-care', name: 'Home Care', icon: 'Home', image: MEDICAL_ILLUSTRATIONS.homeCare },
  { id: 'clinics', name: 'Clinics', icon: 'Building2', image: MEDICAL_ILLUSTRATIONS.clinic },
  { id: 'rehab', name: 'Rehab Center', icon: 'Activity', image: MEDICAL_ILLUSTRATIONS.rehab },
  { id: 'post-surgery', name: 'Post-Surgery', icon: 'Activity', image: MEDICAL_ILLUSTRATIONS.postSurgery },
  { id: 'wound-heal', name: 'Wound Heal', icon: 'Plus', image: MEDICAL_ILLUSTRATIONS.woundCare },
];

export const CARE_CIRCLE = [
  { id: 'cc-1', name: 'Family Medical Ledger', description: 'Centralized clinical history for all dependents.', icon: 'Users' },
  { id: 'cc-2', name: 'Emergency Dispatch', description: 'One-tap trauma response and ambulance coordination.', icon: 'Siren' },
  { id: 'cc-3', name: 'Insurance Synergy', description: 'Unified claim tracking and policy management.', icon: 'ShieldCheck' },
];

export const ACADEMY_CATEGORIES = [
  { id: 'all', name: 'All', icon: 'LayoutGrid' },
  { id: 'yoga', name: 'Yoga', icon: 'Activity' },
  { id: 'diet', name: 'Nutrition', icon: 'Apple' },
  { id: 'cardio', name: 'Cardio', icon: 'HeartPulse' },
  { id: 'mental', name: 'Mindset', icon: 'Brain' },
  { id: 'recorded', name: 'Binge', icon: 'MonitorPlay' },
];

export const doctors = [
  {
    id: 'doc-1',
    name: 'Dr. Ananya Rao',
    title: 'Senior Cardiologist',
    hospital: 'Arogyon Heart Institute',
    area: 'Jubilee Hills',
    rating: '4.9',
    wait: '12 min',
    fee: 'INR 900',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80',
    systemId: 'clinical',
    tag: 'Heart rhythm & Cardiology',
    specialty: 'Cardiology',
    exp: '15 Years',
    lat: 17.4320,
    lng: 78.4075,
    distance: '1.2 km',
  },
  {
    id: 'doc-2',
    name: 'Dr. Ramesh Gupta',
    title: 'Senior Pulmonologist',
    hospital: 'Arogyon Pulmonary Care',
    area: 'Banjara Hills',
    rating: '4.8',
    wait: '15 min',
    fee: 'INR 800',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&q=80',
    systemId: 'clinical',
    tag: 'Lungs & Pulmonology Specialist',
    specialty: 'Pulmonology',
    exp: '14 Years',
    lat: 17.4125,
    lng: 78.4310,
    distance: '2.5 km',
  },
  {
    id: 'doc-3',
    name: 'Dr. Kavitha Reddy',
    title: 'Obstetrician & Gynecologist',
    hospital: 'Arogyon Mother Care',
    area: 'Alipiri Road',
    rating: '4.9',
    wait: '10 min',
    fee: 'INR 750',
    image: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?w=600&q=80',
    systemId: 'clinical',
    tag: 'Gynecology & Pregnancy Care',
    specialty: 'Gynecology',
    exp: '12 Years',
    lat: 13.6405,
    lng: 79.4080,
    distance: '0.8 km',
  },
  {
    id: 'doc-4',
    name: 'Dr. Amit Shah',
    title: 'Neuropsychiatrist',
    hospital: 'Arogyon Mind Center',
    area: 'Madhapur',
    rating: '4.7',
    wait: '20 min',
    fee: 'INR 1000',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80',
    systemId: 'clinical',
    tag: 'Mental Health & Brain Health',
    specialty: 'Mental Health',
    exp: '11 Years',
    lat: 17.4420,
    lng: 78.3900,
    distance: '3.1 km',
  },
  {
    id: 'doc-5',
    name: 'Dr. Priya Sharma',
    title: 'Sexual Wellness Specialist',
    hospital: 'Arogyon Wellness Clinic',
    area: 'Hitech City',
    rating: '4.9',
    wait: '8 min',
    fee: 'INR 850',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80',
    systemId: 'clinical',
    tag: 'Hormonal Health & Sexual Wellness',
    specialty: 'Sexual Wellness',
    exp: '10 Years',
    lat: 17.4485,
    lng: 78.3912,
    distance: '1.5 km',
  },
  {
    id: 'doc-6',
    name: 'Dr. Sanjay Sen',
    title: 'Senior Pediatrician',
    hospital: 'Arogyon Kids Clinic',
    area: 'Alipiri Road',
    rating: '4.9',
    wait: '6 min',
    fee: 'INR 700',
    image: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=600&q=80',
    systemId: 'clinical',
    tag: 'Pediatrics & Neonatology Expert',
    specialty: 'Pediatrics',
    exp: '16 Years',
    lat: 13.6410,
    lng: 79.4082,
    distance: '0.9 km',
  },
  {
    id: 'doc-7',
    name: 'Dr. Harish Verma',
    title: 'Gastroenterology specialist',
    hospital: 'Arogyon Gastro Clinic',
    area: 'Jubilee Hills',
    rating: '4.8',
    wait: '11 min',
    fee: 'INR 950',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=600&q=80',
    systemId: 'clinical',
    tag: 'Stomach, liver & digestive track care',
    specialty: 'Gastroenterology',
    exp: '13 Years',
    lat: 17.4330,
    lng: 78.4080,
    distance: '1.4 km',
  },
  {
    id: 'doc-8',
    name: 'Dr. Meera Nair',
    title: 'Allergist & Immunologist',
    hospital: 'Arogyon Allergy Center',
    area: 'Banjara Hills',
    rating: '4.9',
    wait: '5 min',
    fee: 'INR 800',
    image: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?w=600&q=80',
    systemId: 'clinical',
    tag: 'Food Allergy & Asthma Treatment',
    specialty: 'Food Allergy',
    exp: '11 Years',
    lat: 17.4130,
    lng: 78.4320,
    distance: '2.8 km',
  }
];

export const hospitals = [
  {
    id: 'hosp-1',
    name: 'Segi Multi-Speciality',
    area: 'Hitech City',
    promise: 'Cardiology, neurology & diagnostics',
    time: 'Open 24x7',
    departments: '18 departments',
    nextSlot: 'Next slot 5:30 PM',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=900&q=80',
    systemId: 'clinical',
    lat: 17.4485,
    lng: 78.3912,
    distance: '0.8 km',
    isEmergency: true,
  },
  {
    id: 'hosp-2',
    name: 'AyurLife Nature Cure',
    area: 'Madhapur',
    promise: 'Traditional Ayurveda, detoxification and wellness',
    time: '8 AM - 8 PM',
    departments: '5 systems',
    nextSlot: 'Next slot 10:00 AM',
    image: 'https://images.unsplash.com/photo-1544161515-4ae6ce6ca606?w=900&q=80',
    systemId: 'ayurveda',
    lat: 17.4420,
    lng: 78.3900,
    distance: '4.2 km',
  },
];

export const services = [
  { 
    id: 'svc-1', 
    name: 'Cardiac Ambulance', 
    detail: '24/7 cardiac-ready ambulances with paramedical support.', 
    price: '24/7 Emergency', 
    category: 'Clinical',
    image: 'https://images.unsplash.com/photo-1587350859728-117622bc786e?w=800&q=80',
    promise: 'Reached in 12 mins'
  },
  { 
    id: 'svc-2', 
    name: 'Home Blood Test', 
    detail: 'Home sample collection covering 64+ vital markers.', 
    price: 'Starts ₹899', 
    category: 'Diagnostics',
    image: 'https://images.unsplash.com/photo-1579152276503-3467b6eb98bb?w=800&q=80',
    promise: 'NABL Certified Labs'
  },
  { 
    id: 'svc-3', 
    name: 'Elderly Care Assistant', 
    detail: 'Professional caregivers for post-op and long-term home support.', 
    price: '₹15,000 / mo', 
    category: 'Home Care',
    image: 'https://images.unsplash.com/photo-1581578731522-745505146317?w=800&q=80',
    promise: 'Verified professionals'
  },
  { 
    id: 'svc-4', 
    name: 'Family Health Shield', 
    detail: 'Annual insurance covering hospital cash and daily care.', 
    price: '₹2,499 / yr', 
    category: 'Insurance',
    image: 'https://images.unsplash.com/photo-1556742049-02e53f40d99d?w=800&q=80',
    promise: 'Instant claim setup'
  },
  { 
    id: 'svc-5', 
    name: 'Therapeutic Massage', 
    detail: 'Ancient self-care rituals combined with modern physio.', 
    price: '₹1,200', 
    category: 'Self Care',
    image: 'https://images.unsplash.com/photo-1544161515-4ae6ce6ca606?w=800&q=80',
    promise: 'Expert Hands'
  },
  { 
    id: 'svc-6', 
    name: 'Homeopathy Consult', 
    detail: 'Natural systemic healing with 1:1 expert consultation.', 
    price: '₹300 / sess', 
    category: 'Homeopathy',
    image: 'https://images.unsplash.com/photo-1576091160550-217359f49a4c?w=800&q=80',
    promise: 'Holistic Approach'
  },
];

export const courses = [
  { 
    id: 'course-1', 
    name: 'Heart Smart Diet Mastery', 
    mode: 'Monthly', 
    duration: '14 days', 
    mentor: 'Dr. Ananya Rao', 
    price: '₹2,999', 
    sessions: 'Daily 10 AM',
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80',
    systemId: 'clinical',
    isRecommended: true,
  },
  { 
    id: 'course-2', 
    name: 'Restorative Yoga Program', 
    mode: 'Live', 
    duration: '4 weeks', 
    mentor: 'Segi Physio Team', 
    price: '₹199 / sess', 
    sessions: '3x Weekly',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    systemId: 'ayurveda',
    isRecommended: true,
  },
  { 
    id: 'course-3', 
    name: 'Diabetes Care Foundation', 
    mode: 'Monthly', 
    duration: '3 months', 
    mentor: 'Clinical Desk', 
    price: '₹4,500', 
    sessions: 'Live + Video',
    image: 'https://images.unsplash.com/photo-1505751172107-16d41829f046?w=800&q=80',
    systemId: 'clinical'
  },
  { 
    id: 'course-4', 
    name: 'Stress-Free Mindset', 
    mode: 'Recorded', 
    duration: '10 Modules', 
    mentor: 'Holistic Health Desk', 
    price: '₹899', 
    sessions: 'Binge Watch',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    systemId: 'homeopathy'
  }
];

export const coursesExpanded = [
  { id: 'ce-1', name: 'Guided Meditation', type: 'Video', duration: '10 mins', views: '2.4k' },
  { id: 'ce-2', name: 'Breathing Basics', type: 'Video', duration: '15 mins', views: '1.8k' },
];

export const labPackages = [
  {
    id: 'lp-1',
    name: 'Full Body Checkup',
    tag: 'POPULAR',
    testCount: 64,
    tests: ['Liver Function', 'Kidney Function', 'Diabetes', 'Cardiac'],
    image: 'https://images.unsplash.com/photo-1579152276503-3467b6eb98bb?w=400&q=80',
    price: '₹1,599',
    oldPrice: '₹2,999',
    available: 'Today',
    type: 'popular',
    homeCollection: true
  },
  {
    id: 'lp-2',
    name: 'Advanced Heart Care',
    tag: 'BEST VALUE',
    testCount: 12,
    tests: ['Lipid Profile', 'ECG', 'TMT', 'CBC'],
    image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e024?w=400&q=80',
    price: '₹2,499',
    oldPrice: '₹4,500',
    available: 'Tomorrow',
    type: 'cardiac',
    homeCollection: true
  },
  {
    id: 'lp-3',
    name: 'Women Health Special',
    tag: 'SPECIAL CARE',
    testCount: 48,
    tests: ['Thyroid', 'Vitamin D & B12', 'CBC', 'Iron Profile'],
    image: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?w=400&q=80',
    price: '₹1,899',
    oldPrice: '₹3,200',
    available: 'Today',
    type: 'popular',
    homeCollection: false
  }
];

export const pharmacyItems = [
  {
    id: 'ph-1',
    name: 'Paracetamol 500mg',
    brand: 'Crocin',
    dosage: '15 tablets',
    price: '₹42',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    type: 'otc'
  },
  {
    id: 'ph-2',
    name: 'Vitamin C + Zinc',
    brand: 'Limcee',
    dosage: '30 tablets',
    price: '₹180',
    image: 'https://images.unsplash.com/photo-1616679902298-636824946752?w=400&q=80',
    type: 'vitamins'
  },
  {
    id: 'ph-3',
    name: 'Omega 3 Fish Oil',
    brand: 'TrueBasics',
    dosage: '60 capsules',
    price: '₹699',
    image: 'https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=400&q=80',
    type: 'vitamins'
  },
  {
    id: 'ph-4',
    name: 'Ibuprofen 400mg',
    brand: 'Combiflam',
    dosage: '20 tablets',
    price: '₹38',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    type: 'otc'
  }
];

export const insurancePackages = [
  {
    id: 'ins-1',
    name: 'Family Health Shield Plus',
    provider: 'Star Health Insurance',
    coverage: 'Up to ₹10 Lakhs',
    premium: '₹499/mo',
    coPay: '0% Co-Pay',
    hospitalsCount: '140+ network hospitals',
    image: 'https://images.unsplash.com/photo-1454165833968-3860bb4d380f?w=400&q=80',
    type: 'family',
    cashless: true
  },
  {
    id: 'ins-2',
    name: 'Critical Illness Coverage',
    provider: 'HDFC Ergo Care',
    coverage: 'Up to ₹25 Lakhs',
    premium: '₹799/mo',
    coPay: 'No medical test required',
    hospitalsCount: '200+ network hospitals',
    image: 'https://images.unsplash.com/photo-1556742049-02e53f40d99d?w=400&q=80',
    type: 'critical',
    cashless: true
  },
  {
    id: 'ins-3',
    name: 'Senior Citizen Care Plan',
    provider: 'Niva Bupa Health',
    coverage: 'Up to ₹5 Lakhs',
    premium: '₹899/mo',
    coPay: '10% Co-Pay',
    hospitalsCount: '90+ network hospitals',
    image: 'https://images.unsplash.com/photo-1581578731522-745505146317?w=400&q=80',
    type: 'family',
    cashless: false
  }
];


export const others = [
  {
    id: 'other-1',
    name: 'Rithika Sen',
    title: 'Senior Dietician & Clinical Nutritionist',
    hospital: 'Arogyon Nutrition Desk',
    area: 'Jubilee Hills',
    rating: '4.9',
    wait: '10 min',
    fee: 'INR 600',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80',
    systemId: 'diet',
    tag: 'Custom diet plans, weight management & metabolic care',
    specialty: 'Dietician',
    exp: '8 Years',
    lat: 17.4320,
    lng: 78.4075,
    distance: '1.2 km',
  },
  {
    id: 'other-2',
    name: 'Dr. Madhavan Nair',
    title: 'Ayurvedic Diet & Lifestyle Consultant',
    hospital: 'AyurLife Nature Cure',
    area: 'Banjara Hills',
    rating: '4.8',
    wait: '15 min',
    fee: 'INR 500',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=600&q=80',
    systemId: 'ayurveda',
    tag: 'Panchakarma diet, traditional wellness & holistic cure',
    specialty: 'Ayurveda Dietician',
    exp: '12 Years',
    lat: 17.4125,
    lng: 78.4310,
    distance: '2.5 km',
  },
  {
    id: 'other-3',
    name: 'Vikram Rathore',
    title: 'Elite Strength & Weight Management Coach',
    hospital: 'Triangle Fitness & Wellness Center',
    area: 'Madhapur',
    rating: '4.9',
    wait: '5 min',
    fee: 'INR 800',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80',
    systemId: 'fitness',
    tag: 'Strength training, active rehab & fat loss coaching',
    specialty: 'Weight & Fitness',
    exp: '10 Years',
    lat: 17.4420,
    lng: 78.3900,
    distance: '3.1 km',
  },
  {
    id: 'other-4',
    name: 'Triangle Fitness Gym',
    title: 'Premium Multi-Speciality Gym & Rehab Hub',
    hospital: 'Triangle Gyms Network',
    area: 'Hitech City',
    rating: '4.8',
    wait: '6 AM - 10 PM',
    fee: 'INR 1500 / mo',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80',
    systemId: 'gym',
    tag: 'Fully equipped cardio, strength & premium physical training sections',
    specialty: 'Gym Center',
    exp: 'Modern Facility',
    lat: 17.4485,
    lng: 78.3912,
    distance: '1.5 km',
  },
  {
    id: 'other-5',
    name: 'Anjali Desai',
    title: 'Vinyasa & Ashtanga Yoga Acharya',
    hospital: 'Arogyon Yoga Shala',
    area: 'Banjara Hills',
    rating: '4.9',
    wait: 'Morning slots',
    fee: 'INR 400 / class',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80',
    systemId: 'yoga',
    tag: 'Pranayama, power yoga, flexibility coaching & mental clarity',
    specialty: 'Yoga & Meditation',
    exp: '9 Years',
    lat: 17.4125,
    lng: 78.4310,
    distance: '2.4 km',
  },
  {
    id: 'other-6',
    name: 'Rahul Khanna',
    title: 'Licensed Zumba® & Dance Cardio Coach',
    hospital: 'Triangle Dance & Cardio Arena',
    area: 'Hitech City',
    rating: '4.8',
    wait: 'Evening classes',
    fee: 'INR 500 / class',
    image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&q=80',
    systemId: 'dance',
    tag: 'High-intensity zumba, rhythmic cardio & fat burn sessions',
    specialty: 'Dance & Cardio',
    exp: '6 Years',
    lat: 17.4485,
    lng: 78.3912,
    distance: '1.6 km',
  }
];
