export const SPECIALTY_ILLUSTRATIONS = {
  generalPhysician: require('../assets/images/medical-theme/specialties/general-physician.png'),
  cardiology: require('../assets/images/medical-theme/specialties/cardiology.png'),
  ophthalmology: require('../assets/images/medical-theme/specialties/ophthalmology.png'),
  dentistry: require('../assets/images/medical-theme/specialties/dentistry.png'),
  generalSurgery: require('../assets/images/medical-theme/specialties/general-surgery.png'),
  oncology: require('../assets/images/medical-theme/specialties/oncology.png'),
  pediatrics: require('../assets/images/medical-theme/specialties/pediatrics.png'),
  orthopedics: require('../assets/images/medical-theme/specialties/orthopedics.png'),
  gynecology: require('../assets/images/medical-theme/specialties/gynecology.png'),
  neurology: require('../assets/images/medical-theme/specialties/neurology.png'),
  urology: require('../assets/images/medical-theme/specialties/urology.png'),
  dermatology: require('../assets/images/medical-theme/specialties/dermatology.png'),
  entCare: require('../assets/images/medical-theme/specialties/ent-care.png'),
  psychiatry: require('../assets/images/medical-theme/specialties/psychiatry.png'),
  diabetology: require('../assets/images/medical-theme/specialties/diabetology.png'),
  gastroenterology: require('../assets/images/medical-theme/specialties/gastroenterology.png'),
  pulmonology: require('../assets/images/medical-theme/specialties/pulmonology.png'),
  nephrology: require('../assets/images/medical-theme/specialties/nephrology.png'),
} as const;

export const SITUATION_ILLUSTRATIONS = {
  accident: require('../assets/images/medical-theme/situations/accident.png'),
  fever: require('../assets/images/medical-theme/situations/fever.png'),
  poisoning: require('../assets/images/medical-theme/situations/poisoning.png'),
  chestPain: require('../assets/images/medical-theme/situations/chest-pain.png'),
  breathing: require('../assets/images/medical-theme/situations/breathing.png'),
  stomachAche: require('../assets/images/medical-theme/situations/stomach-ache.png'),
  fracture: require('../assets/images/medical-theme/situations/fracture.png'),
  migraine: require('../assets/images/medical-theme/situations/migraine.png'),
  skinBurn: require('../assets/images/medical-theme/situations/skin-burn.png'),
  allergy: require('../assets/images/medical-theme/situations/allergy.png'),
  bpCrisis: require('../assets/images/medical-theme/situations/bp-crisis.png'),
  animalBite: require('../assets/images/medical-theme/situations/animal-bite.png'),
  pimpleAcne: require('../assets/images/medical-theme/situations/pimple-and-acne.png'),
  hairLoss: require('../assets/images/medical-theme/situations/hair-loss.png'),
  sexualHealth: require('../assets/images/medical-theme/situations/sexual-health.png'),
  periodPain: require('../assets/images/medical-theme/situations/period-pain.png'),
  weightCare: require('../assets/images/medical-theme/situations/weight-care.png'),
  stressAnxiety: require('../assets/images/medical-theme/situations/stress-and-anxiety.png'),
  acidityGas: require('../assets/images/medical-theme/situations/acidity-and-gas.png'),
  toothache: require('../assets/images/medical-theme/situations/toothache.png'),
} as const;
