export const SITUATION_ILLUSTRATIONS = {
  accident: require('../assets/images/medical-theme/situations/accident.png'),
  fever: require('../assets/images/medical-theme/situations/fever.png'),
  poisoning: require('../assets/images/medical-theme/situations/poisoning.png'),
  chestPain: require('../assets/images/medical-theme/situations/chest-pain.png'),
  breathing: require('../assets/images/medical-theme/situations/breathing.png'),
  stomachAche: require('../assets/images/medical-theme/situations/stomach-ache.png'),
  fracture: require('../assets/images/medical-theme/situations/fracture.png'),
  migraine: require('../assets/images/medical-theme/situations/migraine.png'),
  skinBurn: require('../assets/images/medical-theme/situations/skin-burn.png'),
  allergy: require('../assets/images/medical-theme/situations/allergy.png'),
  bpCrisis: require('../assets/images/medical-theme/situations/bp-crisis.png'),
  animalBite: require('../assets/images/medical-theme/situations/animal-bite.png'),
  pimpleAcne: require('../assets/images/medical-theme/situations/pimple-and-acne.png'),
  hairLoss: require('../assets/images/medical-theme/situations/hair-loss.png'),
  sexualHealth: require('../assets/images/medical-theme/situations/sexual-health.png'),
  periodPain: require('../assets/images/medical-theme/situations/period-pain.png'),
  weightCare: require('../assets/images/medical-theme/situations/weight-care.png'),
  stressAnxiety: require('../assets/images/medical-theme/situations/stress-and-anxiety.png'),
  acidityGas: require('../assets/images/medical-theme/situations/acidity-and-gas.png'),
  toothache: require('../assets/images/medical-theme/situations/toothache.png'),
} as const;
