export interface OfferCategory {
  id: string;
  name: string;
  image: any;
  iconType?: string;
}

export interface OfferDoctor {
  id: string;
  name: string;
  specialty: string;
  specialtyId: string;
  qualification: string;
  experience: string;
  hospital: string;
  location: string;
  rating: string;
  reviewsCount: string;
  originalPrice: number;
  discountedPrice: number;
  discountPercentage: number;
  image: string;
  nextAvailable: string;
  isInstantVideo: boolean;
  languages: string[];
  tags: string[];
}

export const OFFER_CATEGORIES: OfferCategory[] = [
  {
    id: 'all',
    name: 'All',
    image: require('@/assets/images/category-icons/general-physician.png'),
  },
  {
    id: 'general-physician',
    name: 'Physician',
    image: require('@/assets/images/category-icons/general-physician.png'),
  },
  {
    id: 'dermatology',
    name: 'Derma',
    image: require('@/assets/images/category-icons/skin-specialist.png'),
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics',
    image: require('@/assets/images/category-icons/child-care.png'),
  },
  {
    id: 'gynecology',
    name: 'Gynecology',
    image: require('@/assets/images/category-icons/womens-health.png'),
  },
  {
    id: 'cardiology',
    name: 'Cardio',
    image: require('@/assets/images/category-icons/heart-specialist.png'),
  },
  {
    id: 'orthopedics',
    name: 'Ortho',
    image: require('@/assets/images/category-icons/bones-joints.png'),
  },
  {
    id: 'dentistry',
    name: 'Dentist',
    image: require('@/assets/images/category-icons/dentist.png'),
  },
  {
    id: 'eye-care',
    name: 'Eye Care',
    image: require('@/assets/images/category-icons/eye-specialist.png'),
  },
  {
    id: 'ent',
    name: 'ENT',
    image: require('@/assets/images/category-icons/ent.png'),
  },
  {
    id: 'diabetes',
    name: 'Diabetes',
    image: require('@/assets/images/category-icons/diabetes.png'),
  },
  {
    id: 'mental-health',
    name: 'Mental',
    image: require('@/assets/images/category-icons/mental-wellness.png'),
  },
];

export const OFFER_DOCTORS: OfferDoctor[] = [
  {
    id: 'doc-off-1',
    name: 'Dr. Ananya Rao',
    specialty: 'Senior Cardiologist',
    specialtyId: 'cardiology',
    qualification: 'MD (Cardiology), DM, AIIMS',
    experience: '15 Years Exp',
    hospital: 'Arogyon Heart Institute',
    location: 'Jubilee Hills, Hyderabad',
    rating: '4.9',
    reviewsCount: '240+',
    originalPrice: 1000,
    discountedPrice: 500,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80',
    nextAvailable: 'Available in 10 mins',
    isInstantVideo: true,
    languages: ['English', 'Hindi', 'Telugu'],
    tags: ['Heart Care', 'Hypertension', 'ECG Review'],
  },
  {
    id: 'doc-off-2',
    name: 'Dr. Ramesh Gupta',
    specialty: 'Senior General Physician',
    specialtyId: 'general-physician',
    qualification: 'MBBS, MD (Internal Medicine)',
    experience: '14 Years Exp',
    hospital: 'Apollo Clinic',
    location: 'Banjara Hills, Hyderabad',
    rating: '4.8',
    reviewsCount: '310+',
    originalPrice: 800,
    discountedPrice: 400,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&q=80',
    nextAvailable: 'Available in 15 mins',
    isInstantVideo: true,
    languages: ['English', 'Hindi'],
    tags: ['Fever', 'Cough & Cold', 'General Health'],
  },
  {
    id: 'doc-off-3',
    name: 'Dr. Kavitha Reddy',
    specialty: 'Obstetrician & Gynecologist',
    specialtyId: 'gynecology',
    qualification: 'MBBS, MS (OBG), DNB',
    experience: '12 Years Exp',
    hospital: 'Cloudnine Care Hospital',
    location: 'Indiranagar, Bangalore',
    rating: '4.9',
    reviewsCount: '190+',
    originalPrice: 900,
    discountedPrice: 450,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1594824813573-246434de83fb?w=600&q=80',
    nextAvailable: 'Today at 4:30 PM',
    isInstantVideo: false,
    languages: ['English', 'Kannada', 'Hindi'],
    tags: ['PCOS', 'Pregnancy Checkup', 'Women Health'],
  },
  {
    id: 'doc-off-4',
    name: 'Dr. Rohan Mehra',
    specialty: 'Consultant Dermatologist',
    specialtyId: 'dermatology',
    qualification: 'MD (Dermatology, Venereology & Leprosy)',
    experience: '9 Years Exp',
    hospital: 'Kaya Skin & Derma Clinic',
    location: 'Koramangala, Bangalore',
    rating: '4.9',
    reviewsCount: '410+',
    originalPrice: 1100,
    discountedPrice: 550,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80',
    nextAvailable: 'Available in 5 mins',
    isInstantVideo: true,
    languages: ['English', 'Hindi'],
    tags: ['Acne Treatment', 'Hair Fall', 'Skin Glow'],
  },
  {
    id: 'doc-off-5',
    name: 'Dr. Sanjay Sen',
    specialty: 'Senior Pediatrician & Neonatologist',
    specialtyId: 'pediatrics',
    qualification: 'MBBS, DCH, MD (Pediatrics)',
    experience: '16 Years Exp',
    hospital: 'Rainbow Children\'s Hospital',
    location: 'HSR Layout, Bangalore',
    rating: '4.9',
    reviewsCount: '350+',
    originalPrice: 850,
    discountedPrice: 425,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=600&q=80',
    nextAvailable: 'Available in 20 mins',
    isInstantVideo: true,
    languages: ['English', 'Hindi', 'Bengali'],
    tags: ['Vaccination', 'Child Nutrition', 'Infant Care'],
  },
  {
    id: 'doc-off-6',
    name: 'Dr. Arjun Reddy',
    specialty: 'Joint Replacement & Orthopedic Surgeon',
    specialtyId: 'orthopedics',
    qualification: 'MS (Ortho), Fellowship in Arthroscopy',
    experience: '13 Years Exp',
    hospital: 'Manipal Hospital',
    location: 'Whitefield, Bangalore',
    rating: '4.8',
    reviewsCount: '165+',
    originalPrice: 1200,
    discountedPrice: 600,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=600&q=80',
    nextAvailable: 'Today at 6:00 PM',
    isInstantVideo: false,
    languages: ['English', 'Telugu', 'Kannada'],
    tags: ['Knee Pain', 'Back Pain', 'Fractures'],
  },
  {
    id: 'doc-off-7',
    name: 'Dr. Shruti Deshmukh',
    specialty: 'Chief Dental Surgeon',
    specialtyId: 'dentistry',
    qualification: 'BDS, MDS (Prosthodontics)',
    experience: '8 Years Exp',
    hospital: 'Clove Dental Care',
    location: 'Indiranagar, Bangalore',
    rating: '4.9',
    reviewsCount: '280+',
    originalPrice: 600,
    discountedPrice: 300,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80',
    nextAvailable: 'Available in 12 mins',
    isInstantVideo: true,
    languages: ['English', 'Hindi', 'Marathi'],
    tags: ['Teeth Cleaning', 'Root Canal', 'Braces'],
  },
  {
    id: 'doc-off-8',
    name: 'Dr. Rajesh Nair',
    specialty: 'Senior Eye Surgeon & Ophthalmologist',
    specialtyId: 'eye-care',
    qualification: 'MS (Ophthalmology), FRCS',
    experience: '18 Years Exp',
    hospital: 'Dr. Agarwal\'s Eye Hospital',
    location: 'Koramangala, Bangalore',
    rating: '4.9',
    reviewsCount: '320+',
    originalPrice: 900,
    discountedPrice: 450,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=600&q=80',
    nextAvailable: 'Tomorrow at 10:30 AM',
    isInstantVideo: false,
    languages: ['English', 'Malayalam', 'Tamil'],
    tags: ['Lasik Surgery', 'Cataract', 'Eye Strain'],
  },
  {
    id: 'doc-off-9',
    name: 'Dr. Meera Swaminathan',
    specialty: 'ENT & Head-Neck Specialist',
    specialtyId: 'ent',
    qualification: 'MS (ENT), DNB',
    experience: '11 Years Exp',
    hospital: 'Fortis Hospital',
    location: 'Cunningham Road, Bangalore',
    rating: '4.7',
    reviewsCount: '140+',
    originalPrice: 800,
    discountedPrice: 400,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80',
    nextAvailable: 'Available in 25 mins',
    isInstantVideo: true,
    languages: ['English', 'Hindi', 'Tamil'],
    tags: ['Sinusitis', 'Ear Infection', 'Throat Pain'],
  },
  {
    id: 'doc-off-10',
    name: 'Dr. Vikram Malhotra',
    specialty: 'Diabetologist & Endocrinologist',
    specialtyId: 'diabetes',
    qualification: 'MD, DM (Endocrinology)',
    experience: '14 Years Exp',
    hospital: 'Arogyon Diabetes Hub',
    location: 'HSR Layout, Bangalore',
    rating: '4.8',
    reviewsCount: '215+',
    originalPrice: 1000,
    discountedPrice: 500,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&q=80',
    nextAvailable: 'Available in 30 mins',
    isInstantVideo: true,
    languages: ['English', 'Hindi', 'Punjabi'],
    tags: ['HbA1c Control', 'Diet Plan', 'Insulin Management'],
  },
  {
    id: 'doc-off-11',
    name: 'Dr. Amit Shah',
    specialty: 'Clinical Neuropsychiatrist',
    specialtyId: 'mental-health',
    qualification: 'MD (Psychiatry), DPM',
    experience: '11 Years Exp',
    hospital: 'Arogyon Mind Wellness Center',
    location: 'Madhapur, Hyderabad',
    rating: '4.8',
    reviewsCount: '195+',
    originalPrice: 1200,
    discountedPrice: 600,
    discountPercentage: 50,
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&q=80',
    nextAvailable: 'Today at 5:00 PM',
    isInstantVideo: true,
    languages: ['English', 'Hindi', 'Gujarati'],
    tags: ['Stress & Anxiety', 'Depression', 'Sleep Issues'],
  },
];

export interface OfferHealthPackage {
  id: string;
  title: string;
  category: string;
  categoryId: string;
  summary: string;
  testsCount: number;
  inclusions: string[];
  originalPrice: number;
  discountedPrice: number;
  discountPercentage: number;
  rating: string;
  bookingsCount: string;
  hospitalName: string;
  hospitalLocation: string;
  duration: string;
  hasHomeSample: boolean;
  hasDoctorConsult: boolean;
  image: string;
  badge?: string;
}

export const OFFER_PACKAGE_CATEGORIES: OfferCategory[] = [
  {
    id: 'all',
    name: 'All',
    image: require('@/assets/images/category-icons/general-physician.png'),
  },
  {
    id: 'full-body',
    name: 'Full Body',
    image: require('@/assets/images/category-icons/general-physician.png'),
  },
  {
    id: 'cardiac',
    name: 'Cardiac',
    image: require('@/assets/images/category-icons/heart-specialist.png'),
  },
  {
    id: 'pregnancy',
    name: 'Pregnancy',
    image: require('@/assets/images/category-icons/womens-health.png'),
  },
  {
    id: 'weight-loss',
    name: 'Weight',
    image: require('@/assets/images/category-icons/stomach-digestion.png'),
  },
  {
    id: 'diabetes',
    name: 'Diabetes',
    image: require('@/assets/images/category-icons/diabetes.png'),
  },
  {
    id: 'skin-derma',
    name: 'Derma',
    image: require('@/assets/images/category-icons/skin-specialist.png'),
  },
  {
    id: 'ortho-joint',
    name: 'Joint Care',
    image: require('@/assets/images/category-icons/bones-joints.png'),
  },
  {
    id: 'senior-care',
    name: 'Senior',
    image: require('@/assets/images/category-icons/brain-nerves.png'),
  },
  {
    id: 'dental',
    name: 'Dental',
    image: require('@/assets/images/category-icons/dentist.png'),
  },
  {
    id: 'eye-care',
    name: 'Eye Care',
    image: require('@/assets/images/category-icons/eye-specialist.png'),
  },
];

export const OFFER_PACKAGES: OfferHealthPackage[] = [
  {
    id: 'pkg-off-1',
    title: 'Arogyon Platinum Full Body Health Screening',
    category: 'Full Body Checkup',
    categoryId: 'full-body',
    summary: 'Comprehensive 85+ parameter vital screening with organ function tests and cardiologist review.',
    testsCount: 85,
    inclusions: [
      'Complete Blood Count (CBC)',
      'Liver & Kidney Function Profile',
      'Lipid & Cholesterol Profile',
      'HbA1c & Fasting Glucose',
      'Thyroid Total (T3, T4, TSH)',
      'Vitamin D & B12 Levels',
      'Free Cardiologist In-Clinic Consult',
    ],
    originalPrice: 4999,
    discountedPrice: 2499,
    discountPercentage: 50,
    rating: '4.9',
    bookingsCount: '1.8K+ Booked',
    hospitalName: 'Arogyon Diagnostics Hub',
    hospitalLocation: 'Indiranagar, Bangalore',
    duration: '24 hrs for reports',
    hasHomeSample: true,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=600',
    badge: 'BESTSELLER',
  },
  {
    id: 'pkg-off-2',
    title: 'Advanced Cardiac Wellness & Heart Shield Plan',
    category: 'Cardiac Care',
    categoryId: 'cardiac',
    summary: 'Preventive heart health check with digital ECG, lipid markers and senior cardiologist consult.',
    testsCount: 42,
    inclusions: [
      'Digital 12-Lead ECG Analysis',
      'Lipid Profile & High-Sensitivity CRP',
      'Cardiac Risk Assessment Score',
      'ApoA1 & ApoB Markers',
      'Electrolytes & Renal Function',
      'Senior Cardiologist 1-on-1 Consult',
    ],
    originalPrice: 3999,
    discountedPrice: 1999,
    discountPercentage: 50,
    rating: '4.9',
    bookingsCount: '920+ Booked',
    hospitalName: 'Arogyon Heart Institute',
    hospitalLocation: 'Jubilee Hills, Hyderabad',
    duration: 'Same day reports',
    hasHomeSample: true,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=600',
    badge: 'CARDIAC CARE',
  },
  {
    id: 'pkg-off-3',
    title: 'Complete Trimester 1 & 2 Pregnancy Care Plan',
    category: 'Pregnancy Care',
    categoryId: 'pregnancy',
    summary: 'Full term clinical monitoring, quarterly ultrasounds, nutritionist sessions & obstetrician reviews.',
    testsCount: 35,
    inclusions: [
      'Trimester Ultrasound Schedule',
      'Gestational Glucose Screening',
      'Folic Acid & Iron Serum Panel',
      'Personalized Prenatal Dietitian',
      '24/7 Maternity Emergency Hotline',
      'Lamaze Class Intro Session',
    ],
    originalPrice: 7999,
    discountedPrice: 3999,
    discountPercentage: 50,
    rating: '4.9',
    bookingsCount: '650+ Booked',
    hospitalName: 'Cloudnine Mother & Child Hospital',
    hospitalLocation: 'Koramangala, Bangalore',
    duration: 'Multi-week ongoing',
    hasHomeSample: true,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?q=80&w=600',
    badge: 'MOST POPULAR',
  },
  {
    id: 'pkg-off-4',
    title: 'Metabolic Reset & Active Weight Loss Plan',
    category: 'Weight Loss',
    categoryId: 'weight-loss',
    summary: 'Scientifically calibrated metabolism profiling, body fat analysis, and customized diet review.',
    testsCount: 28,
    inclusions: [
      'Basal Metabolic Rate (BMR) Profiling',
      'Thyroid & Insulin Resistance Index',
      'Visceral Fat & Body Composition Scan',
      '1-on-1 Clinical Dietitian Diet Plan',
      'Weekly Progress Tracking Check-ins',
    ],
    originalPrice: 3499,
    discountedPrice: 1749,
    discountPercentage: 50,
    rating: '4.8',
    bookingsCount: '1.1K+ Booked',
    hospitalName: 'Arogyon Metabolic Center',
    hospitalLocation: 'HSR Layout, Bangalore',
    duration: '90 Days Program',
    hasHomeSample: true,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=600',
    badge: 'HIGH DEMAND',
  },
  {
    id: 'pkg-off-5',
    title: 'Comprehensive Diabetes Reversal & Shield Plan',
    category: 'Diabetes Care',
    categoryId: 'diabetes',
    summary: 'Continuous glucose monitoring insights, microalbumin panel, eye fundus screening & dietitian guidance.',
    testsCount: 52,
    inclusions: [
      'HbA1c & Fasting Insulin Panel',
      'Kidney Microalbumin Urine Ratio',
      'Digital Diabetic Retinopathy Screen',
      'Peripheral Neuropathy Foot Exam',
      'Diabetologist Prescription Plan',
    ],
    originalPrice: 4200,
    discountedPrice: 2100,
    discountPercentage: 50,
    rating: '4.8',
    bookingsCount: '840+ Booked',
    hospitalName: 'Apollo Sugar Clinics',
    hospitalLocation: 'Banjara Hills, Hyderabad',
    duration: '24 hrs for reports',
    hasHomeSample: true,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=600',
    badge: 'CLINICAL SHIELD',
  },
  {
    id: 'pkg-off-6',
    title: 'Glow Skin & Hair Rejuvenation Assessment',
    category: 'Derma & Skin Care',
    categoryId: 'skin-derma',
    summary: 'Clinical trichoscopy scalp assessment, sebum level analysis, hormone profiling and derma review.',
    testsCount: 22,
    inclusions: [
      'High-Magnification Trichoscopy Scan',
      'Serum Ferritin & Vitamin D3 Check',
      'Skin Barrier & Hydration Analysis',
      'Senior Dermatologist Personalized Regime',
      'Medicated Skincare Product Voucher',
    ],
    originalPrice: 2999,
    discountedPrice: 1499,
    discountPercentage: 50,
    rating: '4.9',
    bookingsCount: '1.4K+ Booked',
    hospitalName: 'Kaya Skin Clinic',
    hospitalLocation: 'Indiranagar, Bangalore',
    duration: 'Same day assessment',
    hasHomeSample: false,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1512290900676-26c2a6a095ae?q=80&w=600',
    badge: 'TRENDING',
  },
  {
    id: 'pkg-off-7',
    title: 'Senior Citizen Comprehensive Vital Shield (60+)',
    category: 'Senior Care',
    categoryId: 'senior-care',
    summary: 'Specially designed for elderly wellness with bone density DEXA screening, cardiac and kidney review.',
    testsCount: 68,
    inclusions: [
      'DEXA Bone Mineral Density Scan',
      'Cardiac Stress Marker Profile',
      'Renal & Hepatic Extended Profile',
      'Hearing & Vision Acuity Check',
      'Home Nurse Sample Collection Free',
      'Geriatric Specialist Consultation',
    ],
    originalPrice: 5999,
    discountedPrice: 2999,
    discountPercentage: 50,
    rating: '4.9',
    bookingsCount: '780+ Booked',
    hospitalName: 'Manipal Hospital',
    hospitalLocation: 'Whitefield, Bangalore',
    duration: 'Priority 12 hrs reports',
    hasHomeSample: true,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1581579438747-1dc8d1e058ca?q=80&w=600',
    badge: 'SENIOR WELLNESS',
  },
  {
    id: 'pkg-off-8',
    title: 'Knee Mobility & Joint Health Comprehensive Package',
    category: 'Orthopedic & Joint Care',
    categoryId: 'ortho-joint',
    summary: 'Standing bilateral digital X-ray, uric acid & inflammatory markers, paired with physio assessment.',
    testsCount: 18,
    inclusions: [
      'Digital Standing Bilateral Knee X-Ray',
      'Serum Uric Acid & ESR / RA Factor',
      'Calcium & Vitamin D Panel',
      '30-Min Ortho Physio Mobility Session',
      'Senior Orthopedic Surgeon Review',
    ],
    originalPrice: 3200,
    discountedPrice: 1600,
    discountPercentage: 50,
    rating: '4.8',
    bookingsCount: '510+ Booked',
    hospitalName: 'Fortis Healthcare',
    hospitalLocation: 'Cunningham Road, Bangalore',
    duration: 'Same day reports',
    hasHomeSample: false,
    hasDoctorConsult: true,
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=600',
    badge: 'MOBILITY CARE',
  },
];

