/**
 * Arogyon Master Package & Category Index Registry
 * Centralized indexing for all medical categories, custom banners, wide cards, and health package IDs.
 */

export interface PackageItem {
  id: string;
  categoryId: string;
  title: string;
  price: string;
  originalPrice: string;
  discount: string;
  image: string;
  hospitalName: string;
  hospitalLocation: string;
  testsCount: number;
  inclusions: string[];
  summary: string;
}

export interface CategoryIndex {
  id: string;
  aliases: string[];
  title: string;
  subtitle: string;
  heroImage: string;
  offer: string;
  cardColors: [string, string, ...string[]];
  cardBadge: string;
  packages: PackageItem[];
}

export const CATEGORY_INDEX_REGISTRY: Record<string, CategoryIndex> = {
  skin: {
    id: 'skin',
    aliases: ['derma', 'dermatology', 'skincare'],
    title: 'SKIN & DERMATOLOGY CARE PLANS',
    subtitle: 'Clinical acne treatment, laser therapy & dermatology packages',
    heroImage: 'https://images.unsplash.com/photo-1512290900676-26c2a4d4b5b3?q=80&w=1000',
    offer: '40% OFF DERMA CARE UNLOCKED',
    cardColors: ['#FFF0F5', '#F8D7E5'],
    cardBadge: '40% OFF DERMA',
    packages: [
      {
        id: 'derma-acne-glow-package',
        categoryId: 'skin',
        title: 'Clinical Acne & Hydrafacial Glow Care',
        price: '₹2,999',
        originalPrice: '₹5,500',
        discount: '45% OFF',
        image: 'https://images.unsplash.com/photo-1512290900676-26c2a4d4b5b3?q=80&w=600',
        hospitalName: 'Kaya Skin Clinic',
        hospitalLocation: 'Indiranagar, Bangalore',
        testsCount: 6,
        inclusions: ['Dermatologist Consultation', 'Deep Pore Cleansing', 'LED Therapy', 'Post-Care Serum Kit'],
        summary: 'Comprehensive clinical skin care for acne reduction, skin hydration, and hyperpigmentation control.',
      },
      {
        id: 'derma-laser-skin-toning',
        categoryId: 'skin',
        title: 'Advanced Laser Toning & Pigmentation Removal',
        price: '₹4,999',
        originalPrice: '₹8,500',
        discount: '41% OFF',
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=600',
        hospitalName: 'Apollo Cosmetic Clinic',
        hospitalLocation: 'Jubilee Hills, Hyderabad',
        testsCount: 8,
        inclusions: ['Q-Switched Laser Session', 'Skin Analysis Test', 'Sunscreen Protection Pack'],
        summary: 'Precision laser toning for even skin tone, collagen boost, and blemish reduction.',
      },
    ],
  },
  pregnancy: {
    id: 'pregnancy',
    aliases: ['maternity', 'antenatal', 'obs-gyn'],
    title: 'PREGNANCY & MATERNITY CARE PLANS',
    subtitle: 'Maternity packages, 40-week screening & specialist doctor consults',
    heroImage: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1000',
    offer: '50% OFF UP TO ₹1,500 UNLOCKED',
    cardColors: ['#FCE4EC', '#F8BBD0'],
    cardBadge: '50% OFF MATERNITY',
    packages: [
      {
        id: 'pregnancy-premium-delivery-package',
        categoryId: 'pregnancy',
        title: 'Premium Delivery & Maternity Suite Package',
        price: '₹34,999',
        originalPrice: '₹55,000',
        discount: '36% OFF',
        image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600',
        hospitalName: 'Cloudnine Hospitals',
        hospitalLocation: 'Jayanagar, Bangalore',
        testsCount: 30,
        inclusions: ['Normal / C-Section Delivery', '3 Nights Private Deluxe Suite Stay', 'Gynecologist & Pediatrician Charges'],
        summary: 'Full end-to-end luxury delivery package with private suite, 24x7 nursing care, and newborn care.',
      },
      {
        id: 'pregnancy-trimester-1-2-checkup',
        categoryId: 'pregnancy',
        title: 'Trimester 1 & 2 Complete Fetal Care',
        price: '₹4,999',
        originalPrice: '₹8,500',
        discount: '41% OFF',
        image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=600',
        hospitalName: 'Apollo Cradle',
        hospitalLocation: 'Koramangala, Bangalore',
        testsCount: 18,
        inclusions: ['NT Scan & Double Marker', 'Anomalies Ultrasound Scan', '4x Gynecologist Consultations'],
        summary: 'Comprehensive early pregnancy screening including genetic marker scans, blood profile, and dietary guidance.',
      },
    ],
  },
  cardiac: {
    id: 'cardiac',
    aliases: ['heart', 'cardiology'],
    title: 'CARDIAC & HEART CARE PLANS',
    subtitle: 'ECG, Echo, Angiography & preventive heart diagnostic packages',
    heroImage: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=1000',
    offer: '35% OFF HEART DIAGNOSTICS UNLOCKED',
    cardColors: ['#FFEBEE', '#FFCDD2'],
    cardBadge: '35% OFF HEART CARE',
    packages: [
      {
        id: 'cardiac-advanced-heart-screening',
        categoryId: 'cardiac',
        title: 'Comprehensive Cardiac Health & TMT Check',
        price: '₹2,499',
        originalPrice: '₹4,500',
        discount: '44% OFF',
        image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=600',
        hospitalName: 'Narayana Institute of Cardiac Sciences',
        hospitalLocation: 'Electronic City, Bangalore',
        testsCount: 22,
        inclusions: ['2D Echo with Doppler', 'Treadmill Test (TMT)', 'Lipid Profile', 'Senior Cardiologist Consult'],
        summary: 'Preventive heart package covering coronary risk markers, arterial stiffness, and blood pressure monitoring.',
      },
    ],
  },
  knee: {
    id: 'knee',
    aliases: ['joint-knee', 'knee-replacement'],
    title: 'KNEE & JOINT RECOVERY PLANS',
    subtitle: 'Joint surgery, ACL recovery & physical rehabilitation packages',
    heroImage: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=1000',
    offer: 'FLAT ₹5,000 OFF SURGERY & REHAB',
    cardColors: ['#E0F2F1', '#B2DFDB'],
    cardBadge: '₹5,000 OFF KNEE REHAB',
    packages: [
      {
        id: 'knee-arthroscopy-rehab-plan',
        categoryId: 'knee',
        title: 'Advanced Robotic Knee Surgery & Rehab Plan',
        price: '₹39,999',
        originalPrice: '₹60,000',
        discount: '33% OFF',
        image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=600',
        hospitalName: 'Sparsh Super Speciality Hospital',
        hospitalLocation: 'Yeshwanthpur, Bangalore',
        testsCount: 14,
        inclusions: ['Minimal Invasive Knee Surgery', '3 Days Hospitalization', '10 In-Home Physiotherapy Sessions'],
        summary: 'Complete joint restoration plan with sub-millimeter robotic precision and physical therapy.',
      },
    ],
  },
  diabetes: {
    id: 'diabetes',
    aliases: ['sugar', 'endocrinology'],
    title: 'DIABETES MANAGEMENT PLANS',
    subtitle: 'HbA1c tests, continuous glucose monitoring & endocrinologist plans',
    heroImage: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=1000',
    offer: 'FREE HBA1C TEST INCLUDED',
    cardColors: ['#FFF8E1', '#FFECB3'],
    cardBadge: 'FREE HBA1C TEST',
    packages: [
      {
        id: 'diabetes-annual-care-plan',
        categoryId: 'diabetes',
        title: 'Annual Diabetes Protection & Organ Shield',
        price: '₹1,999',
        originalPrice: '₹3,800',
        discount: '47% OFF',
        image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=600',
        hospitalName: 'Fortis Diabetes Center',
        hospitalLocation: 'Cunningham Rd, Bangalore',
        testsCount: 28,
        inclusions: ['Quarterly HbA1c Tests', 'Diabetic Retinopathy Eye Exam', 'Kidney Microalbumin Test', 'Dietitian Plan'],
        summary: '365-day structured care program preventing diabetic nephropathy, neuropathy, and vision complications.',
      },
    ],
  },
  weight: {
    id: 'weight',
    aliases: ['bariatric', 'fitness', 'slimming'],
    title: 'WEIGHT LOSS & WELLNESS PLANS',
    subtitle: 'Metabolic panels, nutritionist guidance & body composition plans',
    heroImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000',
    offer: '30% OFF NUTRITION CONSULTATION',
    cardColors: ['#F3E5F5', '#E1BEE7'],
    cardBadge: '30% OFF METABOLIC RESET',
    packages: [
      {
        id: 'weight-metabolic-reset-package',
        categoryId: 'weight',
        title: '90-Day Medical Weight Loss & Metabolic Reset',
        price: '₹3,499',
        originalPrice: '₹6,500',
        discount: '46% OFF',
        image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=600',
        hospitalName: 'Manipal Wellness Clinic',
        hospitalLocation: 'HAL Airport Rd, Bangalore',
        testsCount: 16,
        inclusions: ['Thyroid & Hormone Profile', 'InBody DEXA Composition Scan', 'Custom Keto/Intermittent Diet Plan'],
        summary: 'Physician-guided metabolic reset program designed for sustainable fat loss and muscle retention.',
      },
    ],
  },
  ortho: {
    id: 'ortho',
    aliases: ['orthopedics', 'bone'],
    title: 'ORTHOPEDIC CARE PLANS',
    subtitle: 'Bone density, joint replacement & spine therapy packages',
    heroImage: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=1000',
    offer: 'FREE BONE DENSITY SCAN UNLOCKED',
    cardColors: ['#E8EAF6', '#C5CAE9'],
    cardBadge: 'FREE BONE DENSITY SCAN',
    packages: [
      {
        id: 'ortho-bone-joint-health-check',
        categoryId: 'ortho',
        title: 'Senior Bone Density & Spine Alignment Check',
        price: '₹1,999',
        originalPrice: '₹3,500',
        discount: '43% OFF',
        image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=600',
        hospitalName: 'Sakra World Hospital',
        hospitalLocation: 'Bellandur, Bangalore',
        testsCount: 12,
        inclusions: ['DEXA Scan (T-Score)', 'Vitamin D3 & Calcium Level Test', 'Orthopedic Surgeon Consult'],
        summary: 'Advanced bone health evaluation for osteoporosis screening and joint flexibility assessment.',
      },
    ],
  },
  senior: {
    id: 'senior',
    aliases: ['senior-citizen', 'geriatric'],
    title: 'SENIOR CITIZEN HEALTH PLANS',
    subtitle: 'Geriatric comprehensive health screening & home sample collection',
    heroImage: 'https://images.unsplash.com/photo-1581579438747-1dc8d1e2729a?q=80&w=1000',
    offer: 'FREE HOME SAMPLE COLLECTION',
    cardColors: ['#E8F5E9', '#C8E6C9'],
    cardBadge: 'FREE HOME SAMPLE',
    packages: [
      {
        id: 'senior-full-geriatric-eval',
        categoryId: 'senior',
        title: 'Comprehensive Senior Citizen Annual Package',
        price: '₹8,999',
        originalPrice: '₹14,000',
        discount: '35% OFF',
        image: 'https://images.unsplash.com/photo-1581579438747-1dc8d1e2729a?q=80&w=600',
        hospitalName: 'Apollo Senior Care',
        hospitalLocation: 'Bannerghatta Rd, Bangalore',
        testsCount: 45,
        inclusions: ['Full Blood & Kidney Panel', 'ECG & Chest X-Ray', 'Neurology & Hearing Test', 'Home Visit Included'],
        summary: 'Tailored 45-parameter screening designed for individuals above 60 years with free home phlebotomy.',
      },
    ],
  },
  dental: {
    id: 'dental',
    aliases: ['dentistry', 'smile'],
    title: 'DENTAL & SMILE CARE PLANS',
    subtitle: 'Root canal, clear aligners & smile design packages',
    heroImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=1000',
    offer: 'FLAT 50% OFF TEETH CLEANING',
    cardColors: ['#E0F7FA', '#B2EBF2'],
    cardBadge: '50% OFF CLEANING',
    packages: [
      {
        id: 'dental-smile-makeover-aligner',
        categoryId: 'dental',
        title: 'Invisible Clear Aligner & Smile Correction',
        price: '₹39,999',
        originalPrice: '₹60,000',
        discount: '33% OFF',
        image: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=600',
        hospitalName: 'Clove Dental Specialist Center',
        hospitalLocation: 'Indiranagar, Bangalore',
        testsCount: 5,
        inclusions: ['3D Intraoral Scanning', 'Custom Aligner Set', 'Monthly Orthodontist Retainer Check'],
        summary: 'Modern invisible braces solution for teeth straightening without metal wires.',
      },
    ],
  },
  pediatrics: {
    id: 'pediatrics',
    aliases: ['child-care', 'pediatric'],
    title: 'PEDIATRIC & CHILD CARE PLANS',
    subtitle: 'Growth assessment, child vaccination & pediatric consultations',
    heroImage: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=1000',
    offer: 'FLAT 25% OFF VACCINATION & CARE',
    cardColors: ['#FFF3E0', '#FFE0B2'],
    cardBadge: '25% OFF VACCINE',
    packages: [
      {
        id: 'pediatrics-growth-immunization',
        categoryId: 'pediatrics',
        title: 'Child Growth & Complete Immunization Package',
        price: '₹3999',
        originalPrice: '₹6,000',
        discount: '33% OFF',
        image: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=600',
        hospitalName: 'Rainbow Children’s Hospital',
        hospitalLocation: 'Marathahalli, Bangalore',
        testsCount: 10,
        inclusions: ['Pediatric Growth Chart Analysis', 'Essential Vaccination Dose', 'Vision & Hearing Check'],
        summary: 'Specialized wellness package tracking infant milestone development and essential vaccinations.',
      },
    ],
  },
  fitness: {
    id: 'fitness',
    aliases: ['yoga', 'wellness', 'exercise'],
    title: 'FITNESS CARE PLANS',
    subtitle: 'Yoga, posture alignment, functional training & lifestyle wellness',
    heroImage: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=1000',
    offer: '50% OFF UP TO ₹1,500 UNLOCKED',
    cardColors: ['#DCEAD8', '#B7D9AE'],
    cardBadge: '50% OFF FITNESS',
    packages: [
      {
        id: 'fitness-yoga-mastery-package',
        categoryId: 'fitness',
        title: 'Morning Yoga & Posture Alignment Package',
        price: '₹1,999',
        originalPrice: '₹3,999',
        discount: '50% OFF',
        image: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=600',
        hospitalName: 'Cult Fitness Center',
        hospitalLocation: 'Indiranagar, Bangalore',
        testsCount: 4,
        inclusions: ['30 Days Unlimited Yoga Pass', 'Physiotherapy Posture Assessment', 'Personal Dietitian Plan'],
        summary: 'Daily morning guided yoga, posture alignment, and stress reduction training.',
      },
      {
        id: 'fitness-body-rehab-package',
        categoryId: 'fitness',
        title: 'Full Body Functional Strength & Cardio Pack',
        price: '₹3,499',
        originalPrice: '₹6,500',
        discount: '46% OFF',
        image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600',
        hospitalName: 'Gold Gym & Rehab Hub',
        hospitalLocation: 'Jubilee Hills, Hyderabad',
        testsCount: 6,
        inclusions: ['Personal Trainer Sessions', 'BMR & Fat Analysis', 'Supplement Guide'],
        summary: 'Targeted functional training to build stamina, flexibility, and core strength.',
      },
    ],
  },
  surgery: {
    id: 'surgery',
    aliases: ['planned-surgery', 'post-surgery', 'planned_surgery', '5', 'general-surgery', 'general_surgery'],
    title: 'PLANNED SURGERY & CLINICAL CARE',
    subtitle: 'Consult top surgical specialists with 24/7 post-care assistance & 0% EMI options',
    heroImage: 'https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=1000',
    offer: '0% EMI & FREE SURGERY ASSISTANCE UNLOCKED',
    cardColors: ['#EBF5FF', '#D0E1FD'],
    cardBadge: '24/7 SURGERY CARE',
    packages: [
      {
        id: 'surgery-laparoscopic-care',
        categoryId: 'surgery',
        title: 'Advanced Laparoscopic & General Surgery Care',
        price: '₹29,999',
        originalPrice: '₹45,000',
        discount: '33% OFF',
        image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=600',
        hospitalName: 'Manipal Super Speciality Hospital',
        hospitalLocation: 'HAL Airport Rd, Bangalore',
        testsCount: 15,
        inclusions: ['Pre-op Diagnostic Suite', 'Senior Surgeon Consult', 'Deluxe Private Room Stay', 'Post-Op 30-Day Followups'],
        summary: 'Painless minimally invasive surgery package with complete insurance claim desk support.',
      },
    ],
  },
  international: {
    id: 'international',
    aliases: ['international-care', 'international-patient-care', 'medical-tourism', 'global-care'],
    title: 'INTERNATIONAL PATIENT CARE',
    subtitle: 'World-class medical tourism, tele-consults & multi-disciplinary treatment desk',
    heroImage: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=1000',
    offer: 'FREE MEDICAL SECOND OPINION UNLOCKED',
    cardColors: ['#EEF2FF', '#C7D2FE'],
    cardBadge: 'GLOBAL PATIENT DESK',
    packages: [
      {
        id: 'international-second-opinion',
        categoryId: 'international',
        title: 'Global Medical Second Opinion & Visa Desk',
        price: '₹4,999',
        originalPrice: '₹10,000',
        discount: '50% OFF',
        image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=600',
        hospitalName: 'Arogyon Global Care Center',
        hospitalLocation: 'Bengaluru / Hyderabad',
        testsCount: 10,
        inclusions: ['Medical Visa Invitation Letter', 'Airport Transfer & Translator', 'Multi-Disciplinary Tumor Board Review'],
        summary: 'Seamless international patient concierge service connecting global patients to top Indian hospital directors.',
      },
    ],
  },
  preventive: {
    id: 'preventive',
    aliases: ['preventive-health', 'full-body', 'fullbody', 'full_body', 'wellness-care'],
    title: 'PREVENTIVE HEALTH & FULL BODY CARE',
    subtitle: 'Proactive full-body diagnostic checkups paired with 1:1 expert health guidance',
    heroImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1000',
    offer: 'FLAT 55% OFF FULL BODY DIAGNOSTICS',
    cardColors: ['#E6F4EA', '#CEEAD6'],
    cardBadge: '55% OFF FULL BODY',
    packages: [
      {
        id: 'preventive-full-body-executive',
        categoryId: 'preventive',
        title: 'Master Executive Full Body Health Checkup',
        price: '₹3,999',
        originalPrice: '₹8,999',
        discount: '55% OFF',
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=600',
        hospitalName: 'Apollo Diagnostics Hub',
        hospitalLocation: 'Koramangala, Bangalore',
        testsCount: 85,
        inclusions: ['Vitamin D3 & B12', 'Full Lipid & Kidney Panel', 'Liver Function & HbA1c', 'Free Home Sample Pickup'],
        summary: '85+ Vital parameters including organ screening, cardiac risk, and free home phlebotomist visit.',
      },
    ],
  },
  women: {
    id: 'women',
    aliases: ['womens', 'womens-health', 'womens_health', '9', 'gynecology', 'gynaecologist', 'maternity-care'],
    title: "WOMEN'S HEALTH & MATERNITY CARE",
    subtitle: 'Dedicated gynecologists, PCOS/PCOD management & 40-week pregnancy care plans',
    heroImage: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=1000',
    offer: 'FLAT 45% OFF WOMEN WELLNESS',
    cardColors: ['#FCE4EC', '#F8BBD0'],
    cardBadge: 'WOMENS WELLNESS DESK',
    packages: [
      {
        id: 'women-wellness-pcos-checkup',
        categoryId: 'women',
        title: "Comprehensive Women's Hormonal & PCOS Screening",
        price: '₹2,499',
        originalPrice: '₹4,800',
        discount: '48% OFF',
        image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=600',
        hospitalName: 'Cloudnine Women Center',
        hospitalLocation: 'Jayanagar, Bangalore',
        testsCount: 20,
        inclusions: ['Pelvic Ultrasound Scan', 'Thyroid & Hormonal Panel', 'PCOS Diet Consultation'],
        summary: 'Holistic hormonal and reproductive health evaluation designed specifically for women.',
      },
    ],
  },
  men: {
    id: 'men',
    aliases: ['mens', 'mens-health', 'mens_health', 'executive-wellness'],
    title: "MEN'S HEALTH & EXECUTIVE WELLNESS",
    subtitle: 'Specialized prostate, hormonal, heart & lifestyle wellness consultations',
    heroImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000',
    offer: 'FLAT 40% OFF MEN EXECUTIVE CARE',
    cardColors: ['#F3E8FF', '#E9D5FF'],
    cardBadge: 'EXECUTIVE MEN CARE',
    packages: [
      {
        id: 'men-executive-vitality-package',
        categoryId: 'men',
        title: "Men's Executive Health & Prostate Shield",
        price: '₹3,299',
        originalPrice: '₹5,999',
        discount: '45% OFF',
        image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600',
        hospitalName: 'Fortis Healthcare Center',
        hospitalLocation: 'Bannerghatta Rd, Bangalore',
        testsCount: 35,
        inclusions: ['PSA Prostate Scan', 'Testosterone & Serum Level Test', 'Cardio Fitness Assessment'],
        summary: 'Complete executive vitality package evaluating prostate health, cardiac markers, and stamina.',
      },
    ],
  },
  eye: {
    id: 'eye',
    aliases: ['vision', 'ophthalmology', 'cataract', 'lasik', '3'],
    title: 'EYE & VISION CARE PLANS',
    subtitle: 'Lasik surgery, cataract screening & comprehensive eye checkups',
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1000',
    offer: '50% OFF EYE CHECKUP',
    cardColors: ['#E0F2FE', '#BAE6FD'],
    cardBadge: '50% OFF VISION',
    packages: [
      {
        id: 'eye-lasik-vision-check',
        categoryId: 'eye',
        title: 'Advanced Lasik & Cataract Evaluation',
        price: '₹1,499',
        originalPrice: '₹3,000',
        discount: '50% OFF',
        image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=600',
        hospitalName: 'Narayana Nethralaya',
        hospitalLocation: 'Rajajinagar, Bangalore',
        testsCount: 8,
        inclusions: ['Corneal Topography', 'Retina Scan', 'Ophthalmologist Consult'],
        summary: 'Advanced eye diagnostic screening for vision correction and retinal wellness.',
      },
    ],
  },
  gastro: {
    id: 'gastro',
    aliases: ['digestive', 'gastroenterology', 'stomach', 'gut', '22'],
    title: 'GASTRO & DIGESTIVE HEALTH PLANS',
    subtitle: 'Endoscopy, gut health, liver profile & digestive care plans',
    heroImage: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=1000',
    offer: 'FLAT 35% OFF GASTRO CARE',
    cardColors: ['#FEF3C7', '#FDE68A'],
    cardBadge: '35% OFF GASTRO',
    packages: [
      {
        id: 'gastro-gut-health-check',
        categoryId: 'gastro',
        title: 'Complete Gut & Liver Profile Assessment',
        price: '₹2,999',
        originalPrice: '₹4,500',
        discount: '33% OFF',
        image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=600',
        hospitalName: 'Aster CMI Hospital',
        hospitalLocation: 'Hebbal, Bangalore',
        testsCount: 14,
        inclusions: ['Ultrasound Abdomen', 'Liver Function Panel', 'Gastroenterologist Consult'],
        summary: 'Comprehensive stomach, liver, and digestive wellness screening.',
      },
    ],
  },
  hernia: {
    id: 'hernia',
    aliases: ['laparoscopy', 'hernia-surgery'],
    title: 'HERNIA SURGERY & CARE PLANS',
    subtitle: 'Minimally invasive 3D mesh hernia repair & post-op recovery',
    heroImage: 'https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=1000',
    offer: 'FLAT ₹8,000 OFF SURGERY',
    cardColors: ['#F1F5F9', '#E2E8F0'],
    cardBadge: 'HERNIA SURGERY CARE',
    packages: [
      {
        id: 'hernia-repair-package',
        categoryId: 'hernia',
        title: 'Laparoscopic 3D Mesh Hernia Repair Care',
        price: '₹32,999',
        originalPrice: '₹48,000',
        discount: '31% OFF',
        image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=600',
        hospitalName: 'Apollo Hospital',
        hospitalLocation: 'Bannerghatta Rd, Bangalore',
        testsCount: 10,
        inclusions: ['Laparoscopic Mesh Repair', '1 Day Hospitalization', 'Post-Op Followup'],
        summary: 'Fast recovery keyhole hernia repair package with senior surgeon supervision.',
      },
    ],
  },
  mental: {
    id: 'mental',
    aliases: ['psychiatry', 'therapy', 'mind-wellness', '20'],
    title: 'MENTAL WELLNESS & THERAPY PLANS',
    subtitle: '1:1 Confidential therapy, stress management & sleep wellness',
    heroImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1000',
    offer: 'FLAT 40% OFF THERAPY SESSIONS',
    cardColors: ['#F3E8FF', '#E9D5FF'],
    cardBadge: 'CONFIDENTIAL CARE',
    packages: [
      {
        id: 'mental-wellness-session-pack',
        categoryId: 'mental',
        title: '4-Session Confidential Mental Wellness & Therapy',
        price: '₹1,999',
        originalPrice: '₹3,500',
        discount: '43% OFF',
        image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600',
        hospitalName: 'Arogyon Mind Care Desk',
        hospitalLocation: 'Online / In-Person',
        testsCount: 4,
        inclusions: ['4x Clinical Psychologist Sessions', 'Stress & Anxiety Assessment', '24x7 Mindfulness Guide'],
        summary: 'Compassionate 1-on-1 mental wellness therapy for stress, anxiety, and sleep improvement.',
      },
    ],
  },
  oncology: {
    id: 'oncology',
    aliases: ['cancer', 'tumor', 'pet-scan', '6'],
    title: 'CANCER SCREENING & ONCOLOGY CARE PLANS',
    subtitle: 'Early cancer marker screening, PET-CT scans & oncologist consults',
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1000',
    offer: 'EARLY CANCER SCREENING DESK',
    cardColors: ['#FFE4E6', '#FECDD3'],
    cardBadge: 'ONCOLOGY SCREENING',
    packages: [
      {
        id: 'oncology-preventive-cancer-check',
        categoryId: 'oncology',
        title: 'Preventive Tumor Marker & Early Cancer Screening',
        price: '₹5,999',
        originalPrice: '₹11,000',
        discount: '45% OFF',
        image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=600',
        hospitalName: 'HCG Cancer Centre',
        hospitalLocation: 'Kalingarao Rd, Bangalore',
        testsCount: 16,
        inclusions: ['Tumor Marker Blood Screen (CEA/CA-125)', 'Mammogram / Whole Abdomen USG', 'Senior Oncologist Consult'],
        summary: 'Early preventive cancer detection screening with multi-marker blood testing.',
      },
    ],
  },
  rehab: {
    id: 'rehab',
    aliases: ['physiotherapy', 'rehabilitation', 'post-op-rehab'],
    title: 'POST-OPERATIVE REHABILITATION PLANS',
    subtitle: 'In-home physiotherapy, post-surgery rehab & stroke recovery',
    heroImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1000',
    offer: 'FREE IN-HOME PHYSIO VISIT',
    cardColors: ['#CCFBF1', '#99F6E4'],
    cardBadge: 'POST-OP REHAB',
    packages: [
      {
        id: 'rehab-home-physio-pack',
        categoryId: 'rehab',
        title: '10-Session In-Home Physiotherapy & Rehab Pack',
        price: '₹4,999',
        originalPrice: '₹8,000',
        discount: '37% OFF',
        image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=600',
        hospitalName: 'PhysioMotion Care Hub',
        hospitalLocation: 'Home Service Bangalore',
        testsCount: 10,
        inclusions: ['10x In-Home Specialist Visits', 'Mobility & Muscle Strength Assessment', 'Custom Rehab Plan'],
        summary: 'Dedicated door-step physiotherapy recovery for post-surgery and joint rehabilitation.',
      },
    ],
  },
  spine: {
    id: 'spine',
    aliases: ['back-care', 'spine-care', 'disc'],
    title: 'SPINE & BACK CARE PLANS',
    subtitle: 'Disc herniation, spine therapy & posture alignment packages',
    heroImage: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=1000',
    offer: 'FLAT 40% OFF SPINE CARE',
    cardColors: ['#E0E7FF', '#C7D2FE'],
    cardBadge: 'SPINE RECOVERY',
    packages: [
      {
        id: 'spine-mri-decompression-plan',
        categoryId: 'spine',
        title: 'Non-Surgical Spine Decompression & MRI Care',
        price: '₹3,499',
        originalPrice: '₹6,000',
        discount: '41% OFF',
        image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=600',
        hospitalName: 'Qi Spine Clinic',
        hospitalLocation: 'Indiranagar, Bangalore',
        testsCount: 6,
        inclusions: ['Spine Motion Analysis Test', 'Digital MRI Scan Review', '5x Spine Therapy Sessions'],
        summary: 'Targeted non-invasive spine care for back pain, sciatica, and slip disc recovery.',
      },
    ],
  },
  thyroid: {
    id: 'thyroid',
    aliases: ['endocrinologist', 'thyroid-care'],
    title: 'THYROID & HORMONAL CARE PLANS',
    subtitle: 'T3, T4, TSH antibody testing & endocrinologist consults',
    heroImage: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=1000',
    offer: 'FREE THYROID TEST INCLUDED',
    cardColors: ['#FEF9C3', '#FEF08A'],
    cardBadge: 'THYROID SHIELD',
    packages: [
      {
        id: 'thyroid-complete-hormone-panel',
        categoryId: 'thyroid',
        title: 'Complete Thyroid & Anti-TPO Antibody Panel',
        price: '₹799',
        originalPrice: '₹1,800',
        discount: '55% OFF',
        image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=600',
        hospitalName: 'Metropolis Healthcare',
        hospitalLocation: 'Jayanagar, Bangalore',
        testsCount: 8,
        inclusions: ['FT3, FT4 & TSH Ultra', 'Anti-TPO Antibodies', 'Endocrinologist Consult'],
        summary: 'Precision thyroid hormone evaluation for hypothyroidism & hyperthyroidism management.',
      },
    ],
  },
  urology: {
    id: 'urology',
    aliases: ['kidney', 'urinary', 'kidney-stone', '17'],
    title: 'KIDNEY & UROLOGY CARE PLANS',
    subtitle: 'Kidney stone laser removal, prostate care & urology consults',
    heroImage: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=1000',
    offer: 'FLAT 30% OFF UROLOGY CARE',
    cardColors: ['#E0F2FE', '#BAE6FD'],
    cardBadge: 'KIDNEY CARE DESK',
    packages: [
      {
        id: 'urology-kidney-stone-care',
        categoryId: 'urology',
        title: 'Laser Kidney Stone Removal & USG Package',
        price: '₹24,999',
        originalPrice: '₹38,000',
        discount: '34% OFF',
        image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?q=80&w=600',
        hospitalName: 'NU Hospitals Kidney Care',
        hospitalLocation: 'Rajajinagar, Bangalore',
        testsCount: 12,
        inclusions: ['RIRS Laser Stone Lithotripsy', 'KUB Ultrasound Scan', 'Urologist Consult'],
        summary: 'Painless laser kidney stone procedure with same-day discharge option.',
      },
    ],
  },
};

/**
 * Normalizes any category slug/alias (e.g. 'derma' -> 'skin', 'maternity' -> 'pregnancy', 'womens' -> 'women')
 */
export function getCategoryById(inputSlug: string): CategoryIndex {
  const normalized = (inputSlug || '').toLowerCase().trim().replace(/[-_]/g, '');

  // Search by exact key or normalized key
  for (const key in CATEGORY_INDEX_REGISTRY) {
    const keyNormalized = key.toLowerCase().replace(/[-_]/g, '');
    if (keyNormalized === normalized) {
      return CATEGORY_INDEX_REGISTRY[key];
    }
  }

  // Alias lookup (with dash/underscore stripping for ultimate resilience)
  for (const key in CATEGORY_INDEX_REGISTRY) {
    const cat = CATEGORY_INDEX_REGISTRY[key];
    if (cat.aliases.some((alias) => alias.toLowerCase().replace(/[-_]/g, '') === normalized)) {
      return cat;
    }
  }

  // Default fallback category (skin)
  return CATEGORY_INDEX_REGISTRY['skin'];
}

/**
 * Looks up a specific package by its package ID across all categories.
 */
export function getPackageById(packageId: string): PackageItem {
  const targetId = (packageId || '').toLowerCase().trim();

  for (const key in CATEGORY_INDEX_REGISTRY) {
    const category = CATEGORY_INDEX_REGISTRY[key];
    const found = category.packages.find((p) => p.id.toLowerCase() === targetId);
    if (found) return found;
  }

  // Default fallback mock package
  return {
    id: packageId || 'default-package',
    categoryId: 'skin',
    title: 'Comprehensive Medical Package',
    price: '₹14,999',
    originalPrice: '₹19,999',
    discount: '25% OFF',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=600',
    hospitalName: 'Arogyon Partner Hospital',
    hospitalLocation: 'Bangalore / Hyderabad',
    testsCount: 20,
    inclusions: ['Specialist Doctor Consultation', 'Lab Diagnostic Screening', '24x7 Post-Care Support'],
    summary: 'Full-spectrum diagnostic checkup with accredited laboratory testing and senior physician consultation.',
  };
}

/**
 * Returns specialized Add-on Health Packages & Care Plans for appointment checkout screens
 */
export function getAddOnScreeningPackages(): PackageItem[] {
  return [
    {
      id: 'addon-full-body',
      categoryId: 'diabetes',
      title: 'Full Body Vitamin & CBC Screening',
      price: '₹499',
      originalPrice: '₹1,200',
      discount: '58% OFF',
      image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=400',
      hospitalName: 'Apollo Diagnostics',
      hospitalLocation: 'Central Lab',
      testsCount: 60,
      inclusions: ['Vitamin D & B12', 'Thyroid Profile', 'Complete Blood Count (CBC)', 'Fasting Blood Sugar'],
      summary: '60+ Vital Tests including Vitamin D, B12, Thyroid, Blood Count & Sugar',
    },
    {
      id: 'addon-diabetes',
      categoryId: 'diabetes',
      title: 'HbA1c & Fasting Glucose Screening',
      price: '₹299',
      originalPrice: '₹650',
      discount: '54% OFF',
      image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=400',
      hospitalName: 'Thyrocare Labs',
      hospitalLocation: 'Express Hub',
      testsCount: 15,
      inclusions: ['HbA1c Glycated Hemoglobin', 'Fasting Blood Glucose', 'Lipid Profile Summary'],
      summary: 'Comprehensive 3-month average blood sugar & lipid profile assessment',
    },
    {
      id: 'addon-cardiac',
      categoryId: 'cardiac',
      title: 'ECG & Lipid Profile Heart Care',
      price: '₹599',
      originalPrice: '₹1,400',
      discount: '57% OFF',
      image: 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?q=80&w=400',
      hospitalName: 'Narayana Health',
      hospitalLocation: 'Heart Institute',
      testsCount: 22,
      inclusions: ['Resting ECG Scan', 'Cholesterol HDL/LDL', 'Cardiac Risk Markers'],
      summary: 'Resting ECG test with cholesterol, HDL/LDL & cardiac risk markers',
    },
    {
      id: 'addon-derma',
      categoryId: 'skin',
      title: 'Clinical Skin & Hydration Check',
      price: '₹399',
      originalPrice: '₹890',
      discount: '55% OFF',
      image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=400',
      hospitalName: 'Kaya Skin Clinic',
      hospitalLocation: 'Indiranagar',
      testsCount: 6,
      inclusions: ['Dermatology Patch Test', 'Moisture Barrier Check', 'Skin Type Analysis'],
      summary: 'Dermatology patch test, skin moisture barrier check & consult',
    },
  ];
}
